// Runtime boot, shared state selectors and primary application views.
async function snapshotBeforeUpdate(raw){if(!raw||!db)return;const last=raw.meta?.lastAppVersion||'pre-versioning';if(last!==APP_VERSION||Number(raw.version||1)<DATA_VERSION){await idbBackup(raw,`before Atlas ${APP_VERSION} update`)}}
async function load(){try{await openDB();const v=await idbGet();if(v){await snapshotBeforeUpdate(v);state=ensureState(v);state.meta.lastAppVersion=APP_VERSION;await save();}else{let legacy=null;try{legacy=localStorage.getItem('groundOpsControlBoard_v2')||localStorage.getItem('groundOpsControlBoard_v1')}catch(_){ }if(legacy){const parsed=JSON.parse(legacy);await idbBackup(parsed,'before legacy import');state=ensureState(parsed);log('Previous Ground Ops browser data imported into Atlas.')}else{state=ensureState(clone(demo))}state.meta.lastAppVersion=APP_VERSION;await save()}}catch(e){try{const v=localStorage.getItem(FALLBACK_KEY)||localStorage.getItem('groundOpsControlBoard_v2');if(v)state=ensureState(JSON.parse(v));else state=ensureState(clone(demo))}catch(_){state=ensureState(clone(demo))}} renderAll();await initAtlasLock()}
async function save(){state.meta=state.meta||{};state.meta.lastSavedAt=now();state.meta.lastAppVersion=APP_VERSION;state.version=DATA_VERSION;try{if(db)await idbSet(state);else localStorage.setItem(FALLBACK_KEY,JSON.stringify(state))}catch(e){try{localStorage.setItem(FALLBACK_KEY,JSON.stringify(state))}catch(_){}}}
function log(text,profile=state?.settings?.activeProfile||'me'){state.activity.unshift({id:uid('a'),profile,time:now(),text});state.activity=state.activity.slice(0,120)}
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1600)}
function areaById(id){return state.areas.find(a=>a.id===id)} function projectById(id){return state.projects.find(p=>p.id===id)}
function profileById(id){return state.profiles.find(p=>p.id===id)||{id:'me',name:'Me',kind:'person'}} function activeProfile(){return profileById(state.settings.activeProfile||'me')} function profileAllows(profile){return (profile||'me')===(state.settings.activeProfile||'me')}
window.AtlasState=()=>state;
function profileAreas(profile=state.settings.activeProfile||'me'){return state.areas.filter(a=>(a.profile||'me')===profile)}
function profileLinks(profile=state.settings.activeProfile||'me'){return state.links.filter(l=>(l.profile||'me')===profile)}
function areaAllows(a){return !!a&&profileAllows(a.profile)&&spaceAllows(a.space)}
function spaceAllows(space){return state.settings.spaceFilter==='all'||state.settings.spaceFilter===space}
function projectProgress(p){const ms=p.milestones||[]; if(ms.length)return Math.round(ms.filter(m=>m.done).length/ms.length*100);const ts=p.tasks||[];return ts.length?Math.round(ts.filter(t=>t.done).length/ts.length*100):0}
function visibleProjects(scope){return state.projects.filter(p=>profileAllows(p.profile)&&spaceAllows(p.space)&&(!scope||p.areaId===scope||p.topicId===scope||isDescendant(p.topicId||p.areaId,scope)))}
function isDescendant(id,parent){let a=areaById(id),guard=0;while(a&&guard++<12){if(a.parentId===parent)return true;a=areaById(a.parentId)}return false}
function visibleNotes(scope){return state.notes.filter(n=>profileAllows(n.profile)&&spaceAllows(n.space)&&(!scope||n.areaId===scope||n.topicId===scope||isDescendant(n.topicId||n.areaId,scope))).sort((a,b)=>b.createdAt-a.createdAt)}
function statusDot(status){return status==='WATCHING'||status==='MONITOR'?'amber':status==='DORMANT'?'grey':''}
function navItems(){const roots=profileAreas().filter(a=>a.level===2&&a.code!=='DAIL').sort((a,b)=>a.name.localeCompare(b.name));return [...roots.map(a=>({id:a.id,name:a.name})),{id:'daily',name:'Daily'},{id:'calendar',name:'Calendar'},{id:'inbox',name:`Inbox ${inboxCount()?`· ${inboxCount()}`:''}`}]}
function inboxCount(){return state.notes.filter(n=>profileAllows(n.profile)&&!n.areaId).length}

function renderTabs(){
  const items=navItems(),activeTab=state.settings.activeTab==='home'?'':state.settings.activeTab,activeProfileId=state.settings.activeProfile||'me',space=state.settings.spaceFilter||'all';
  const el=document.getElementById('sectionSelect');if(el){el.innerHTML=`<option value="">Navigate</option>`+items.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');el.value=activeTab}
  const ps=document.getElementById('profileSelect');if(ps){ps.innerHTML=state.profiles.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');ps.value=activeProfileId}
  const sf=document.getElementById('spaceFilter');if(sf)sf.value=space;
  const pp=document.getElementById('profileMenuPanel'),pv=document.getElementById('profileMenuValue');if(pp){pp.innerHTML=state.profiles.map(p=>`<button type="button" class="system-item" data-profile-id="${p.id}" aria-current="${p.id===activeProfileId}">${esc(p.name)}</button>`).join('')}if(pv)pv.textContent=profileById(activeProfileId).name;
  const vp=document.getElementById('viewMenuPanel'),vv=document.getElementById('viewMenuValue');if(vp){vp.innerHTML=`<button type="button" class="system-item" data-view-id="" aria-current="${!activeTab}">Home</button>`+items.map(t=>`<button type="button" class="system-item" data-view-id="${t.id}" aria-current="${t.id===activeTab}">${esc(t.name)}</button>`).join('')}if(vv){const t=items.find(x=>x.id===activeTab);vv.textContent=t?t.name:'Navigate'}
  const sp=document.getElementById('spaceMenuPanel'),sv=document.getElementById('spaceMenuValue');const spaces=[['all','All spaces'],['work','Work only'],['personal','Personal only']];if(sp){sp.innerHTML=spaces.map(([id,name])=>`<button type="button" class="system-item" data-space-id="${id}" aria-current="${id===space}">${name}</button>`).join('')}if(sv)sv.textContent=(spaces.find(x=>x[0]===space)||spaces[0])[1];
}

function utilityPaneTitle(tab){return tab==='todo'?'Quick To-do':tab==='upcoming'?'Upcoming':'Scratch'}
function activeScratch(){const pid=state.settings.activeProfile||'me';return state.scratch?.[pid]||''}
function profileQuickTodos(){const pid=state.settings.activeProfile||'me';return (state.quickTodos||[]).filter(t=>(t.profile||'me')===pid).sort((a,b)=>Number(a.done)-Number(b.done)||b.createdAt-a.createdAt)}
function quickUpcoming(days=14){const pid=state.settings.activeProfile||'me',today=todayKey(),until=new Date();until.setDate(until.getDate()+days);const max=until.toLocaleDateString('en-CA');return (state.calendar||[]).filter(e=>(e.profile||'me')===pid&&e.date>=today&&e.date<=max).sort((a,b)=>`${a.date} ${a.startTime||'99:99'}`.localeCompare(`${b.date} ${b.startTime||'99:99'}`)).slice(0,12)}
function applyToolPanePlacement(){
  const pane=document.getElementById('utilityPane'),open=!!(state.settings.sidePane||'');if(!pane)return;
  const dock=['top','left','right','float'].includes(state.settings.toolPaneDock)?state.settings.toolPaneDock:'top';
  state.settings.toolPaneDock=dock;state.settings.toolPaneFloating=dock==='float';
  document.body.classList.toggle('tool-pane-open',open);
  document.body.dataset.toolDock=open?dock:'';
  pane.classList.toggle('floating',open&&dock==='float');
  if(open&&dock==='float'){
    const w=Math.min(380,Math.max(300,pane.offsetWidth||360)),maxX=Math.max(8,window.innerWidth-w-8),maxY=Math.max(66,window.innerHeight-160);
    const x=Number(state.settings.toolPaneX)||Math.max(12,window.innerWidth-w-26),y=Number(state.settings.toolPaneY)||78;
    pane.style.setProperty('left',Math.min(maxX,Math.max(8,x))+'px','important');
    pane.style.setProperty('top',Math.min(maxY,Math.max(62,y))+'px','important');
    pane.style.setProperty('right','auto','important');
  }else{
    pane.style.removeProperty('left');pane.style.removeProperty('top');pane.style.removeProperty('right');
  }
}
function renderUtilityPane(){
  const pane=document.getElementById('utilityPane'),content=document.getElementById('utilityPaneContent'),tab=state.settings.sidePane||'';if(!pane||!content)return;
  document.querySelectorAll('#utilityRail [data-side-tab]').forEach(b=>b.classList.toggle('active',!!tab&&b.dataset.sideTab===tab));
  pane.classList.toggle('open',!!tab);applyToolPanePlacement();if(!tab){content.innerHTML='';return}
  let body='';
  if(tab==='scratch'){body=`<textarea class="scratch-area" id="scratchArea" placeholder="Fast, unstructured thinking…">${esc(activeScratch())}</textarea><div class="utility-help">Autosaves locally to ${esc(activeProfile().name)}. Commit it when it becomes something worth keeping.</div><div class="utility-actions-row"><button type="button" data-side-action="commit-scratch">Commit to Inbox</button><button type="button" data-side-action="clear-scratch">Clear</button></div>`}
  else if(tab==='todo'){const todos=profileQuickTodos();body=`<div class="quick-add"><input id="quickTodoInput" type="text" placeholder="Add a quick task…"><button type="button" data-side-action="add-todo">Add</button></div><div class="quick-list">${todos.length?todos.map(t=>`<label class="quick-todo ${t.done?'done':''}"><input type="checkbox" data-quick-todo="${t.id}" ${t.done?'checked':''}><span>${esc(t.text)}</span><button type="button" data-side-action="delete-todo" data-id="${t.id}" aria-label="Delete task">×</button></label>`).join(''):'<div class="empty">No quick tasks.</div>'}</div><div class="utility-actions-row" style="margin-top:9px"><button type="button" data-side-action="clear-done">Clear done</button></div>`}
  else{const events=quickUpcoming();body=`<div class="quick-upcoming">${events.length?events.map(e=>`<button type="button" class="quick-event" data-calendar-id="${e.id}"><strong>${esc(e.title)}</strong><small>${esc(e.date)}${e.startTime?` · ${esc(e.startTime)}`:''}${e.sourceEventId?' · ENTANGLED':''}</small></button>`).join(''):'<div class="empty">Nothing scheduled in the next 14 days.</div>'}</div>`}
  const dock=state.settings.toolPaneDock||'top';
  content.innerHTML=`<div class="utility-pane-head" data-tool-drag><strong>${utilityPaneTitle(tab)} · ${esc(activeProfile().name)}</strong><div class="tool-window-actions"><details class="tool-dock-menu"><summary>${dock==='float'?'Dock':'Position'}</summary><div class="tool-dock-options">${[['top','Top'],['left','Left'],['right','Right'],['float','Float']].map(([id,label])=>`<button type="button" data-side-action="dock" data-dock="${id}" class="${dock===id?'active':''}">${label}</button>`).join('')}</div></details><button class="utility-pane-close" type="button" data-side-action="close" aria-label="Close">×</button></div></div><div class="utility-pane-body">${body}</div>`;
  applyToolPanePlacement()
}
function setUtilityPane(tab){state.settings.sidePane=state.settings.sidePane===tab?'':tab;if(state.settings.sidePane&&!state.settings.toolPaneDock)state.settings.toolPaneDock='top';save();renderUtilityPane();requestAnimationFrame(()=>{if(state.settings.activeTab==='home'){mapCamera('home').needsFit=true;drawNetwork(null)}})}
function addQuickTodo(){const input=document.getElementById('quickTodoInput');const text=(input?.value||'').trim();if(!text)return;state.quickTodos.unshift({id:uid('qt'),profile:state.settings.activeProfile||'me',text,done:false,createdAt:now()});save();renderUtilityPane()}
function commitScratch(){const text=activeScratch().trim();if(!text)return toast('Scratch pad is empty');const pid=state.settings.activeProfile||'me';state.notes.unshift({id:uid('n'),profile:pid,space:state.settings.spaceFilter==='work'?'work':'personal',areaId:'',topicId:'',type:'note',title:text.split(/\n/)[0].slice(0,70)||'Scratch note',body:text,tags:['Scratch'],createdAt:now(),showOnMap:false});state.scratch[pid]='';log('Scratch committed to Inbox.');save();renderUtilityPane();if(state.settings.activeTab==='inbox')renderInbox();toast('Scratch committed to Inbox')}
function renderAll(){applyTheme();renderTabs();renderUtilityPane();const tab=state.settings.activeTab;if(tab==='home')renderHome();else if(tab==='daily')renderDaily();else if(tab==='calendar')renderCalendar();else if(tab==='inbox')renderInbox();else{const target=areaById(state.settings.selectedArea)||areaById(tab);if(!areaAllows(target)){state.settings.activeTab='home';state.settings.selectedArea='';renderHome()}else renderArea(target.id)}save()}
function metric(label,value,detail){return `<div class="metric"><div class="tiny">${esc(label)}</div><div class="value">${esc(value)}</div></div>`}
function metricsHtml(scope){const ps=visibleProjects(scope),ns=visibleNotes(scope);const active=ps.filter(p=>p.status==='ACTIVE').length;const milestones=ps.flatMap(p=>p.milestones||[]),openM=milestones.filter(m=>!m.done).length;const topics=profileAreas().filter(a=>spaceAllows(a.space)&&(!scope? a.level>=3 : a.parentId===scope)).length;return `<section class="grid metrics">${metric('Active projects',active,'currently moving')}${metric('Open milestones',openM,'across visible projects')}${metric('Linked notes',ns.length,'knowledge records')}${metric('Topics',topics,'visible knowledge nodes')}</section>`}
function queueHtml(items,title,code){return `<div class="panel"><div class="panel-head"><h3>${title}</h3><span class="code">${code}</span></div><div class="queue">${items.length?items.map(i=>`<div class="qrow"><i class="dot ${statusDot(i.status)}"></i><div><div class="qname">${esc(i.name)}</div><div class="qmeta">${esc(i.meta)}</div></div><span class="badge">${esc(i.badge||'OPEN')}</span></div>`).join(''):'<div class="empty">Nothing here.</div>'}</div></div>`}
function getNext(scope){return visibleProjects(scope).filter(p=>p.status==='ACTIVE'||p.status==='WATCHING').slice(0,4).map(p=>({name:p.next||p.title,meta:p.title,status:p.status,badge:p.status}))}
function getWatch(scope){return visibleProjects(scope).filter(p=>p.status!=='COMPLETE').flatMap(p=>(p.milestones||[]).filter(m=>m.current||(!m.done&&p.status==='WATCHING')).slice(0,1).map(m=>({name:m.title,meta:p.title,status:p.status,badge:m.current?'CURRENT':'WATCH'}))).slice(0,4)}

function networkLegendHtml(){const roots=profileAreas().filter(a=>a.level===2&&spaceAllows(a.space)).sort((a,b)=>a.name.localeCompare(b.name)).slice(0,6);return roots.map(a=>`<span><i style="background:${domainHueFor(a)}"></i>${esc(a.code)}</span>`).join('')}
function networkPanel(scope=null){const hero=!scope;const count=graphData(scope).nodes.length;return `<section class="network-stage ${hero?'home-network':'area-network'}">${scope?`<div class="network-head"><h2>${esc(areaById(scope)?.name||'Area')} Network</h2></div>`:''}<div class="map-wrap"><div class="map-meta"><span>MAP</span><span>${esc(activeProfile().name.toUpperCase())}</span><span>${count} NODES</span><span id="mapInspect"></span></div><svg id="network" viewBox="0 0 1200 680" role="img" aria-label="Atlas relationship map"></svg><div class="map-controls"><div class="map-hud"><div class="zoom-controls" aria-label="Map zoom controls"><button type="button" data-map-zoom="out" aria-label="Zoom out">−</button><button type="button" class="zoom-reset" data-map-zoom="reset" aria-label="Fit network"><span id="zoomValue">FIT</span></button><button type="button" data-map-zoom="in" aria-label="Zoom in">+</button></div><div class="zoom-controls" aria-label="Map layout controls"><button type="button" class="zoom-reset" data-map-layout="organise" aria-label="Reform constellation">Reform</button></div><div class="depth">Depth <input id="depthRange" type="range" min="2" max="5" step="1" value="${state.settings.mapDepth}" /><strong id="depthValue">${state.settings.mapDepth}</strong></div><div class="depth map-opacity">Type <input id="labelOpacityRange" type="range" min="0" max="100" step="1" value="${Math.round((state.settings.mapLabelOpacity??.78)*100)}" /><strong id="labelOpacityValue">${Math.round((state.settings.mapLabelOpacity??.78)*100)}</strong></div><div class="depth map-opacity">Links <input id="edgeOpacityRange" type="range" min="0" max="100" step="1" value="${Math.round((state.settings.mapEdgeOpacity??.38)*100)}" /><strong id="edgeOpacityValue">${Math.round((state.settings.mapEdgeOpacity??.38)*100)}</strong></div></div></div></div></section>`}
function foldPanel(title,code,body,open=false){return `<details class="fold" ${open?'open':''}><summary><span>${esc(title)}</span></summary><div class="fold-body">${body}</div></details>`}
function queueRows(items){return `<div class="queue">${items.length?items.map(i=>`<div class="qrow"><i class="dot ${statusDot(i.status)}"></i><div><div class="qname">${esc(i.name)}</div><div class="qmeta">${esc(i.meta)}</div></div><span class="badge">${esc(i.badge||'OPEN')}</span></div>`).join(''):'<div class="empty">Nothing here.</div>'}</div>`}
function upcomingCalendarHtml(){const start=todayKey();const end=new Date();end.setDate(end.getDate()+30);const endKey=end.toLocaleDateString('en-CA');const ev=state.calendar.filter(e=>profileAllows(e.profile)&&e.date>=start&&e.date<=endKey).sort((a,b)=>(a.date+(a.startTime||'')).localeCompare(b.date+(b.startTime||''))).slice(0,8);return `<div class="queue">${ev.length?ev.map(e=>`<div class="qrow"><i class="dot" style="background:${eventHue(e)}"></i><div><div class="qname">${esc(e.title)}${e.entangledId||e.sourceEventId?' ⟷':''}</div><div class="qmeta">${esc(e.date)}${e.startTime?` · ${esc(e.startTime)}`:''}${e.areaId?` · ${esc(areaById(e.areaId)?.name||'')}`:e.sourceAreaLabel?` · ${esc(e.sourceAreaLabel)}`:''}</div></div><span class="badge">${esc(profileById(e.profile).name)}</span></div>`).join(''):'<div class="empty">Nothing scheduled in the next 30 days.</div>'}</div>`}
function renderHome(){const app=document.getElementById('app');const activity=`<div class="notes-list">${state.activity.filter(a=>profileAllows(a.profile)).slice(0,8).map(a=>`<div class="note"><div class="meta">${fmtDate(a.time)} · ${fmtTime(a.time)}</div><div class="note-body">${esc(a.text)}</div></div>`).join('')}</div>`;const dash=`<aside class="home-stack">${foldPanel('Dashboard','',metricsHtml(null),true)}${foldPanel('Upcoming','',upcomingCalendarHtml())}${foldPanel('Active now','',queueRows(getNext(null)))}${foldPanel('Milestones','',queueRows(getWatch(null)))}${foldPanel('Projects','',projectCards(null))}${foldPanel('Recent notes','',notesHtml(visibleNotes(null).slice(0,8)))}${foldPanel('Recent activity','',activity)}</aside>`;app.innerHTML=`<section class="home-layout"><div class="home-map">${networkPanel(null)}</div>${dash}</section>`;drawNetwork(null)}
function childAreas(id){return profileAreas().filter(a=>a.parentId===id&&spaceAllows(a.space))}
function renderArea(id){const a=areaById(id);if(!a){state.settings.activeTab='home';return renderAll()}const subs=['overview','notes','projects','milestones','map'];const app=document.getElementById('app');app.innerHTML=`<div class="workspace-head"><div class="workspace-title"><div class="crumb">ATLAS / ${esc(activeProfile().name.toUpperCase())} / ${esc(a.code)}</div><h2>${esc(a.name)}</h2><p>${esc(a.description)}</p></div><div class="inline-actions"><button class="btn primary" data-quick-add="note" data-area="${a.id}">+ Note</button><button class="btn" data-quick-add="project" data-area="${a.id}">+ Project</button></div></div><nav class="subtabs">${subs.map(s=>`<button class="tab ${state.settings.subtab===s?'active':''}" data-subtab="${s}">${s}</button>`).join('')}</nav><div class="workspace" id="workspace"></div>`;renderWorkspace(a.id)}
function renderWorkspace(id){const el=document.getElementById('workspace');if(!el)return;const st=state.settings.subtab;if(st==='overview'){el.innerHTML=`${metricsHtml(id)}<section class="grid workspace-grid"><div class="panel"><div class="panel-head"><h3>Projects</h3><span class="code">ACTIVE / WATCHING</span></div>${projectCards(id)}</div><div class="side">${queueHtml(getNext(id),'Next moves','PROJECT QUEUE')}${queueHtml(getWatch(id),'Milestones','CURRENT')}</div></section><section class="grid workspace-grid section"><div class="panel"><div class="panel-head"><h3>Recent Notes</h3><span class="code">LINKED</span></div>${notesHtml(visibleNotes(id).slice(0,8))}</div><div class="panel"><div class="panel-head"><h3>Topics</h3><span class="code">CHILD NODES</span></div>${topicsHtml(id)}</div></section>`}
else if(st==='notes')el.innerHTML=`<section class="panel"><div class="panel-head"><h3>Notes</h3><button class="btn small primary" data-quick-add="note" data-area="${id}">+ Add Note</button></div>${notesHtml(visibleNotes(id))}</section>`;
else if(st==='projects')el.innerHTML=`<section class="panel"><div class="panel-head"><h3>Projects</h3><button class="btn small primary" data-quick-add="project" data-area="${id}">+ New Project</button></div>${projectCards(id)}</section>`;
else if(st==='milestones')el.innerHTML=`<section class="panel"><div class="panel-head"><h3>Milestones</h3><span class="code">ALL LINKED PROJECTS</span></div>${milestonesHtml(id)}</section>`;
else if(st==='map'){el.innerHTML=networkPanel(id);if(state.settings.mapViewMode==='nodes')drawNetwork(id);else if(state.settings.mapViewMode==='predict')drawPredictionNetwork(id)}}
function topicsHtml(id){const kids=childAreas(id);return `<div class="topic-grid">${kids.length?kids.map(k=>`<div class="topic" data-open-area="${k.id}"><div class="k">${esc(k.code)} · L${k.level}</div><strong>${esc(k.name)}</strong><span>${esc(k.description)}</span></div>`).join(''):'<div class="empty">No child topics yet.</div>'}</div>`}
function projectCards(scope){const ps=visibleProjects(scope);return `<div class="cards">${ps.length?ps.map(p=>{const pc=projectProgress(p);return `<article class="card clickable" data-project="${p.id}"><div class="card-top"><div><div class="code">${esc(p.code)}</div><h4>${esc(p.title)}</h4></div><span class="badge">${esc(p.status)}</span></div><p>${esc(p.next||p.objective)}</p><div class="progress"><div class="bar" style="width:${pc}%"></div></div><div class="card-foot"><span>${pc}% milestone progress</span><span>${(p.milestones||[]).filter(m=>!m.done).length} open</span></div></article>`}).join(''):'<div class="empty" style="grid-column:1/-1">No projects in this area yet.</div>'}</div>`}
function notesHtml(notes){return `<div class="notes-list">${notes.length?notes.map(n=>`<article class="note"><div class="note-top"><div class="note-title">${esc(n.title||'Untitled')}</div><span class="note-type">${esc(n.type)}</span></div><div class="note-body">${esc(n.body||'')}</div><div class="tags">${(n.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="meta">${fmtDate(n.createdAt)} · ${esc(areaById(n.topicId)?.name||areaById(n.areaId)?.name||'Inbox')}</div></article>`).join(''):'<div class="empty">No notes yet.</div>'}</div>`}
function milestonesHtml(scope){const ps=visibleProjects(scope);const rows=ps.flatMap(p=>(p.milestones||[]).map(m=>({m,p})));return `<div class="milestones">${rows.length?rows.map(({m,p})=>`<div class="mrow"><i class="mark ${m.done?'done':m.current?'current':''}"></i><div><div class="mname">${esc(m.title)}</div><div class="mmeta">${esc(p.title)}</div></div><span class="badge">${m.done?'DONE':m.current?'CURRENT':'OPEN'}</span></div>`).join(''):'<div class="empty">No milestones yet.</div>'}</div>`}

function renderDaily(){const entries=state.daily.filter(d=>profileAllows(d.profile)&&d.date===todayKey()).sort((a,b)=>b.createdAt-a.createdAt);document.getElementById('app').innerHTML=`<div class="workspace-head"><div class="workspace-title"><div class="crumb">ATLAS / ${esc(activeProfile().name.toUpperCase())} / DAILY</div><h2>${new Intl.DateTimeFormat('en-AU',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</h2><p>Capture first. Organise later.</p></div><button class="btn primary" data-quick-add="daily">+ Daily entry</button></div>${metricsHtml(null)}<section class="grid workspace-grid"><div class="panel"><div class="panel-head"><h3>Today</h3><span class="code">${todayKey()}</span></div><div class="daily">${entries.length?entries.map(d=>`<div class="daily-entry"><div class="daily-time">${fmtTime(d.createdAt)} · ${esc(areaById(d.areaId)?.name||'Unlinked')}</div><div class="daily-text">${esc(d.text)}</div></div>`).join(''):'<div class="empty">Nothing captured today.</div>'}</div></div><div class="side">${queueHtml(getNext(null),'Open loops','PROJECTS')}${queueHtml(getWatch(null),'Current milestones','MILESTONES')}</div></section>`}
function renderInbox(){const notes=state.notes.filter(n=>profileAllows(n.profile)&&!n.areaId).sort((a,b)=>b.createdAt-a.createdAt);document.getElementById('app').innerHTML=`<div class="workspace-head"><div class="workspace-title"><div class="crumb">ATLAS / ${esc(activeProfile().name.toUpperCase())} / INBOX</div><h2>Inbox</h2><p>Unsorted notes and ideas. Link them to an area when their home becomes clear.</p></div><button class="btn primary" data-quick-add="note">+ Capture</button></div><section class="panel"><div class="panel-head"><h3>Unsorted</h3><span class="code">${notes.length} ITEMS</span></div>${notesHtml(notes)}</section>`}

