// Atlas Lock: PIN verification, recovery and idle locking.
function bytesToB64(bytes){let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s)}
function b64ToBytes(v){const s=atob(v);return Uint8Array.from(s,c=>c.charCodeAt(0))}
function secureBytes(n=16){const b=new Uint8Array(n);crypto.getRandomValues(b);return b}
async function deriveVerifier(secret,saltB64,iterations=210000){if(!crypto?.subtle)throw new Error('Web Crypto unavailable');const enc=new TextEncoder();const key=await crypto.subtle.importKey('raw',enc.encode(secret),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:b64ToBytes(saltB64),iterations,hash:'SHA-256'},key,256);return bytesToB64(new Uint8Array(bits))}
async function makeVerifier(secret,iterations=210000){const salt=bytesToB64(secureBytes(16));return {salt,verifier:await deriveVerifier(secret,salt,iterations),iterations}}
function safeEqual(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let out=0;for(let i=0;i<a.length;i++)out|=a.charCodeAt(i)^b.charCodeAt(i);return out===0}
function generateRecoveryKey(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const b=secureBytes(20);let s='';for(let i=0;i<20;i++)s+=chars[b[i]%chars.length];return `ATLS-${s.slice(0,4)}-${s.slice(4,8)}-${s.slice(8,12)}-${s.slice(12,16)}-${s.slice(16,20)}`}
let authConfig=null,atlasUnlocked=false,recoveryAuthenticated=false,idleTimer=null,lastActivity=Date.now(),failedAttempts=Number(sessionStorage.getItem('atlas_lock_failures')||0),lockoutUntil=Number(sessionStorage.getItem('atlas_lock_until')||0);
function lockOpen(){document.body.classList.add('atlas-locked');document.getElementById('lockScreen').classList.add('open')}
function lockClose(){document.body.classList.remove('atlas-locked');document.getElementById('lockScreen').classList.remove('open')}
function resetIdleTimer(){lastActivity=Date.now();clearTimeout(idleTimer);if(!atlasUnlocked||!authConfig)return;const mins=Number(authConfig.idleMinutes||0);if(mins>0)idleTimer=setTimeout(()=>lockAtlas('idle'),mins*60000)}
function unlockAtlas(remember=false){atlasUnlocked=true;if(remember)sessionStorage.setItem('atlas_session_unlocked','1');failedAttempts=0;lockoutUntil=0;sessionStorage.removeItem('atlas_lock_failures');sessionStorage.removeItem('atlas_lock_until');lockClose();resetIdleTimer()}
function lockAtlas(reason='manual'){if(!authConfig?.enabled){showSetupScreen();return}atlasUnlocked=false;recoveryAuthenticated=false;sessionStorage.removeItem('atlas_session_unlocked');clearTimeout(idleTimer);showUnlockScreen(reason)}
function authMessage(msg){const e=document.getElementById('lockMessage');if(e)e.textContent=msg||''}
function currentLockoutSeconds(){return Math.max(0,Math.ceil((lockoutUntil-Date.now())/1000))}
function recordFailedAttempt(){failedAttempts+=1;sessionStorage.setItem('atlas_lock_failures',String(failedAttempts));let seconds=0;if(failedAttempts>=5)seconds=30;else if(failedAttempts>=3)seconds=5;if(seconds){lockoutUntil=Date.now()+seconds*1000;sessionStorage.setItem('atlas_lock_until',String(lockoutUntil))}return seconds}
function pinMarkup(id,autocomplete='off'){return `<div class="lock-field"><label>PIN</label><input class="pin-input" id="${id}" type="password" inputmode="numeric" pattern="[0-9]*" maxlength="4" autocomplete="${autocomplete}" aria-label="4 digit PIN"></div>`}
function cleanPinInput(el){if(!el)return'';const v=(el.value||'').replace(/\D/g,'').slice(0,4);if(el.value!==v)el.value=v;return v}
function wirePinInput(id,onComplete){const el=document.getElementById(id);if(!el)return;el.addEventListener('input',()=>{const v=cleanPinInput(el);if(v.length===4&&onComplete)setTimeout(onComplete,60)});setTimeout(()=>el.focus(),60)}
function showSetupScreen(){lockOpen();document.getElementById('lockContent').innerHTML=`<h2 class="lock-title">Set 4-digit PIN</h2>${pinMarkup('setupPin','new-password')}${pinMarkup('setupConfirm','new-password')}<div class="lock-field"><label>Auto-lock</label><select id="setupIdle" aria-label="Auto-lock after inactivity"><option value="5">5 min</option><option value="15" selected>15 min</option><option value="30">30 min</option><option value="60">1 hour</option><option value="0">Never</option></select></div><div class="lock-actions"><button class="lock-primary" id="createLockBtn">Set PIN</button></div><div class="lock-message" id="lockMessage"></div>`;document.getElementById('createLockBtn').addEventListener('click',createAtlasLock);wirePinInput('setupPin');wirePinInput('setupConfirm',()=>{if(cleanPinInput(document.getElementById('setupPin')).length===4)createAtlasLock()})}
async function createAtlasLock(){const p=cleanPinInput(document.getElementById('setupPin')),c=cleanPinInput(document.getElementById('setupConfirm'));if(!/^\d{4}$/.test(p)){authMessage('Enter four digits.');return}if(p!==c){authMessage('PINs do not match.');return}const btn=document.getElementById('createLockBtn');btn.disabled=true;authMessage('');try{const pv=await makeVerifier(p,180000);const recovery=generateRecoveryKey();const rv=await makeVerifier(recovery,160000);authConfig={enabled:true,mode:'pin',pin:pv,recovery:rv,idleMinutes:Number(document.getElementById('setupIdle').value),createdAt:Date.now(),updatedAt:Date.now()};await authSet(authConfig);showRecoveryScreen(recovery)}catch(e){authMessage('Lock could not be created.');btn.disabled=false}}
function showRecoveryScreen(key){lockOpen();document.getElementById('lockContent').innerHTML=`<h2 class="lock-title">Recovery key</h2><p class="lock-copy">Save this somewhere separate.</p><div class="recovery-key">${key}</div><div class="lock-actions"><button class="lock-primary" id="recoverySavedBtn">Done</button></div>`;document.getElementById('recoverySavedBtn').addEventListener('click',()=>unlockAtlas(false))}
function showUnlockScreen(reason='startup'){lockOpen();document.getElementById('lockContent').innerHTML=`${pinMarkup('unlockPin','current-password')}<div class="lock-actions"><button class="lock-primary" id="unlockBtn">Unlock</button><button class="lock-secondary" id="recoveryModeBtn">Recovery</button></div><div class="lock-message" id="lockMessage"></div>`;document.getElementById('unlockBtn').addEventListener('click',attemptUnlock);document.getElementById('recoveryModeBtn').addEventListener('click',showRecoveryUnlock);wirePinInput('unlockPin',attemptUnlock);setTimeout(()=>{const wait=currentLockoutSeconds();if(wait){const b=document.getElementById('unlockBtn');if(b)b.disabled=true;authMessage(`${wait}s`);setTimeout(()=>showUnlockScreen(reason),wait*1000+100)}},50)}
async function attemptUnlock(){const wait=currentLockoutSeconds();if(wait){authMessage(`${wait}s`);return}const p=cleanPinInput(document.getElementById('unlockPin'));if(!/^\d{4}$/.test(p))return authMessage('4 digits');const btn=document.getElementById('unlockBtn');btn.disabled=true;try{const verifier=authConfig.pin||authConfig.password;const v=await deriveVerifier(p,verifier.salt,verifier.iterations);if(safeEqual(v,verifier.verifier)){recoveryAuthenticated=false;unlockAtlas(false);return}const delay=recordFailedAttempt();authMessage(delay?`Try again in ${delay}s`:'Incorrect PIN');setTimeout(()=>showUnlockScreen('startup'),delay?delay*1000+100:500)}catch(e){authMessage('Unable to verify PIN');btn.disabled=false}}
function showRecoveryUnlock(){document.getElementById('lockContent').innerHTML=`<h2 class="lock-title">Recovery</h2><div class="lock-field"><label>Recovery key</label><input id="recoveryInput" type="text" autocomplete="off" spellcheck="false" aria-label="Recovery key"></div><div class="lock-actions"><button class="lock-primary" id="recoveryUnlockBtn">Continue</button><button class="lock-secondary" id="backUnlockBtn">Back</button></div><div class="lock-message" id="lockMessage"></div>`;document.getElementById('recoveryUnlockBtn').addEventListener('click',attemptRecoveryUnlock);document.getElementById('backUnlockBtn').addEventListener('click',()=>showUnlockScreen('startup'));document.getElementById('recoveryInput').addEventListener('keydown',e=>{if(e.key==='Enter')attemptRecoveryUnlock()});setTimeout(()=>document.getElementById('recoveryInput')?.focus(),50)}
function showRecoveryPinReset(){document.getElementById('lockContent').innerHTML=`<h2 class="lock-title">Set new PIN</h2>${pinMarkup('recoveryPin','new-password')}${pinMarkup('recoveryPinConfirm','new-password')}<div class="lock-actions"><button class="lock-primary" id="recoverySetPinBtn">Set PIN</button></div><div class="lock-message" id="lockMessage"></div>`;document.getElementById('recoverySetPinBtn').addEventListener('click',async()=>{const p=cleanPinInput(document.getElementById('recoveryPin')),c=cleanPinInput(document.getElementById('recoveryPinConfirm'));if(!/^\d{4}$/.test(p))return authMessage('Enter four digits');if(p!==c)return authMessage('PINs do not match');authConfig.pin=await makeVerifier(p,180000);authConfig.mode='pin';delete authConfig.password;authConfig.updatedAt=Date.now();await authSet(authConfig);recoveryAuthenticated=false;unlockAtlas(false);toast('PIN updated')});wirePinInput('recoveryPin');wirePinInput('recoveryPinConfirm')}
async function attemptRecoveryUnlock(){const raw=document.getElementById('recoveryInput').value.trim().toUpperCase();if(!raw)return authMessage('Enter recovery key');try{const v=await deriveVerifier(raw,authConfig.recovery.salt,authConfig.recovery.iterations);if(safeEqual(v,authConfig.recovery.verifier)){recoveryAuthenticated=true;showRecoveryPinReset();return}authMessage('Recovery key not recognised')}catch(e){authMessage('Unable to verify recovery key')}}
function showPinMigrationScreen(){lockOpen();document.getElementById('lockContent').innerHTML=`<h2 class="lock-title">Switch to 4-digit PIN</h2><p class="lock-copy">One-time lock update.</p><div class="lock-field"><label>Current password</label><input id="legacyPassword" type="password" autocomplete="current-password" aria-label="Current Atlas password"></div>${pinMarkup('migratePin','new-password')}${pinMarkup('migratePinConfirm','new-password')}<div class="lock-actions"><button class="lock-primary" id="migratePinBtn">Update</button><button class="lock-secondary" id="migrateRecoveryBtn">Recovery</button></div><div class="lock-message" id="lockMessage"></div>`;document.getElementById('migratePinBtn').addEventListener('click',migrateLegacyPasswordToPin);document.getElementById('migrateRecoveryBtn').addEventListener('click',showRecoveryUnlock);wirePinInput('migratePin');wirePinInput('migratePinConfirm');setTimeout(()=>document.getElementById('legacyPassword')?.focus(),60)}
async function migrateLegacyPasswordToPin(){const old=document.getElementById('legacyPassword').value,p=cleanPinInput(document.getElementById('migratePin')),c=cleanPinInput(document.getElementById('migratePinConfirm'));if(!old)return authMessage('Enter current password');if(!/^\d{4}$/.test(p))return authMessage('Enter four digits');if(p!==c)return authMessage('PINs do not match');try{const v=await deriveVerifier(old,authConfig.password.salt,authConfig.password.iterations);if(!safeEqual(v,authConfig.password.verifier))return authMessage('Current password is incorrect');authConfig.pin=await makeVerifier(p,180000);authConfig.mode='pin';delete authConfig.password;authConfig.updatedAt=Date.now();await authSet(authConfig);unlockAtlas(false);toast('Atlas Lock updated to PIN')}catch(e){authMessage('Unable to update lock')}}
async function initAtlasLock(){authConfig=await authGet();if(!authConfig){showSetupScreen();return}if(authConfig.enabled===false){atlasUnlocked=true;lockClose();return}if(authConfig.password&&!authConfig.pin){showPinMigrationScreen();return}if(sessionStorage.getItem('atlas_session_unlocked')==='1'){unlockAtlas(true);return}showUnlockScreen('startup')}
