// Calendar and Entangle linked-event behaviour.
function monthCursorDate(){const raw=state.settings.calendarCursor;if(raw&&/^\d{4}-\d{2}$/.test(raw)){const[y,m]=raw.split('-').map(Number);return new Date(y,m-1,1)}const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)}
function setCalendarCursor(d){state.settings.calendarCursor=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function calendarEvents(profile=state.settings.activeProfile){return state.calendar.filter(e=>(e.profile||'me')===profile).sort((a,b)=>(a.date+a.startTime).localeCompare(b.date+b.startTime))}
function eventHue(e){const a=areaById(e.areaId);return a?domainHueFor({id:a.id}):(e.profile==='us'?'#8e887e':'#7f898d')}
function renderCalendar(){const d=monthCursorDate(),year=d.getFullYear(),month=d.getMonth(),first=new Date(year,month,1),start=new Date(year,month,1-first.getDay());const events=calendarEvents();let cells='';for(let i=0;i<42;i++){const day=new Date(start);day.setDate(start.getDate()+i);const key=day.toLocaleDateString('en-CA'),out=day.getMonth()!==month,today=key===todayKey();const ev=events.filter(e=>e.date===key);cells+=`<div class="cal-cell ${out?'out':''} ${today?'today':''}" data-calendar-date="${key}"><div class="cal-day">${day.getDate()}</div>${ev.map(e=>`<button class="cal-event ${e.entangledId||e.sourceEventId?'cal-entangled':''}" style="--event-hue:${eventHue(e)}" data-calendar-event="${e.id}">${esc(e.title)}<small>${esc(e.startTime||'All day')}${e.areaId?` · ${esc(areaById(e.areaId)?.code||'')}`:e.sourceAreaLabel?` · ${esc(makeNodeCode(e.sourceAreaLabel))}`:''}</small></button>`).join('')}</div>`}const monthTitle=new Intl.DateTimeFormat('en-AU',{month:'long',year:'numeric'}).format(first);document.getElementById('app').innerHTML=`<div class="calendar-head"><div><div class="crumb">ATLAS / ${esc(activeProfile().name.toUpperCase())} / CALENDAR</div><h2>${esc(monthTitle)}</h2></div><div class="calendar-toolbar"><button class="btn small" data-cal-nav="prev">←</button><button class="btn small" data-cal-nav="today">Today</button><button class="btn small" data-cal-nav="next">→</button><button class="btn primary" data-cal-add="${todayKey()}">+ Event</button></div></div><div class="calendar-grid">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="cal-weekday">${x}</div>`).join('')}${cells}</div>`}
let activeCalendarEventId='';
function populateCalendarArea(value=''){const sel=document.getElementById('calArea');sel.innerHTML=`<option value="">Unlinked</option>`+profileAreas().filter(a=>a.level>=2&&spaceAllows(a.space)).sort((a,b)=>a.name.localeCompare(b.name)).map(a=>`<option value="${a.id}" ${a.id===value?'selected':''}>${esc(a.name)} · ${esc(a.code)}</option>`).join('')}
function openCalendarEvent(id='',date=''){activeCalendarEventId=id;const e=id?state.calendar.find(x=>x.id===id):null;const profile=e?.profile||state.settings.activeProfile||'me';document.getElementById('calendarEventHeading').textContent=e?'Edit event':'New event';document.getElementById('calendarEventCode').textContent=`CALENDAR / ${profileById(profile).name.toUpperCase()}`;document.getElementById('calTitle').value=e?.title||'';document.getElementById('calDate').value=e?.date||date||todayKey();document.getElementById('calStart').value=e?.startTime||'';document.getElementById('calEnd').value=e?.endTime||'';populateCalendarArea(e?.areaId||'');document.getElementById('calNotes').value=e?.notes||'';const own=profile!=='us';document.getElementById('entangleRow').style.display=own?'flex':'none';document.getElementById('calEntangle').checked=!!e?.entangledId;document.getElementById('deleteCalendarEvent').style.display=e?'inline-block':'none';document.getElementById('calendarProfileHint').textContent=e?.sourceEventId?'ENTANGLED FROM '+profileById(state.calendar.find(x=>x.id===e.sourceEventId)?.profile||'me').name.toUpperCase():`PROFILE / ${profileById(profile).name.toUpperCase()}`;openOverlay('calendarOverlay');setTimeout(()=>document.getElementById('calTitle').focus(),60)}
function linkedUsEvent(source){return source.entangledId?state.calendar.find(e=>e.id===source.entangledId):state.calendar.find(e=>e.sourceEventId===source.id&&e.profile==='us')}
function syncEntangledEvent(source,enabled){let shared=linkedUsEvent(source);if(!enabled){if(shared)state.calendar=state.calendar.filter(e=>e.id!==shared.id);source.entangledId='';return}if(!shared){shared={id:uid('cal'),profile:'us',sourceEventId:source.id,createdAt:now()};state.calendar.push(shared);source.entangledId=shared.id}Object.assign(shared,{title:source.title,date:source.date,startTime:source.startTime,endTime:source.endTime,areaId:'',sourceAreaLabel:areaById(source.areaId)?.name||'',notes:source.notes,updatedAt:now(),sourceEventId:source.id,profile:'us'})}
function saveCalendarEvent(){const title=document.getElementById('calTitle').value.trim();if(!title)return toast('Add an event title');let e=activeCalendarEventId?state.calendar.find(x=>x.id===activeCalendarEventId):null;if(!e){e={id:uid('cal'),profile:state.settings.activeProfile||'me',createdAt:now()};state.calendar.push(e)}Object.assign(e,{title,date:document.getElementById('calDate').value||todayKey(),startTime:document.getElementById('calStart').value,endTime:document.getElementById('calEnd').value,areaId:document.getElementById('calArea').value,notes:document.getElementById('calNotes').value.trim(),updatedAt:now()});if(e.profile!=='us'&&!e.sourceEventId)syncEntangledEvent(e,document.getElementById('calEntangle').checked);log(`Calendar event saved: ${e.title}.`);save();closeOverlay('calendarOverlay');renderAll();toast(e.entangledId?'Event entangled with Us':'Calendar saved')}
function deleteCalendarEvent(){const e=state.calendar.find(x=>x.id===activeCalendarEventId);if(!e)return;if(!confirm(`Delete ${e.title}?`))return;if(e.entangledId)state.calendar=state.calendar.filter(x=>x.id!==e.entangledId);if(e.sourceEventId){const src=state.calendar.find(x=>x.id===e.sourceEventId);if(src)src.entangledId=''}state.calendar=state.calendar.filter(x=>x.id!==e.id);save();closeOverlay('calendarOverlay');renderAll();toast('Event deleted')}
