// Atlas Sync v3: one Shared Atlas in the cloud, with epoch-gated stale-client quarantine.
(function(root){
  'use strict';
  const Core=root.AtlasSyncV2Core;if(!Core)return;
  const ENTITY_TYPE='entity_state_v2',META_TYPE='entity_sync_v2_meta',META_ID='baseline';
  const BASE_PREFIX='atlas_entity_sync_v3_base:';
  const DEVICE_KEY='atlas_entity_sync_v2_device';
  const PAGE_SIZE=400;
  let client=null,target=null,ready=false,loaded=false,busy=false,recoveryRequired=false,pollTimer=null,pushTimer=null,localSeq=0,lastMessage='';

  const online=()=>typeof navigator==='undefined'||navigator.onLine!==false;
  const localFingerprint=()=>Core.canonical(Core.flattenState(state));
  const localStillSame=(seq,fp)=>localSeq===seq&&localFingerprint()===fp;
  function deviceId(){try{let id=localStorage.getItem(DEVICE_KEY);if(id)return id;id=(crypto?.randomUUID?.()||`device-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`);localStorage.setItem(DEVICE_KEY,id);return id}catch(_){return`volatile-${Math.random().toString(36).slice(2,9)}`}}
  function emit(stateName,message,extra={}){lastMessage=message;const detail={state:stateName,message,joined:ready,dirty:stateName==='PENDING'||stateName==='SYNCING',recordLevel:true,recoveryRequired,...extra};try{root.dispatchEvent(new CustomEvent('atlascanonicalstatus',{detail}))}catch(_){}return detail}

  async function ensureClient(){if(client)return client;const config=root.ATLAS_CLOUD_CONFIG,lib=root.supabase;if(!config?.url||!config?.publishableKey||typeof lib?.createClient!=='function')throw new Error('Atlas cloud client unavailable.');client=lib.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return client}
  async function resolveTarget(){await ensureClient();let {data,error}=await client.auth.getSession();if(error)throw error;let session=data?.session||null;if(!session){const shared=await root.AtlasCloud?.getSession?.();if(shared?.access_token&&shared?.refresh_token){const set=await client.auth.setSession({access_token:shared.access_token,refresh_token:shared.refresh_token});if(set.error)throw set.error;session=set.data?.session||null}}if(!session?.user)throw new Error('Sign in to Atlas cloud first.');const user=session.user;const vault=await client.from('atlas_vaults').select('id').eq('created_by',user.id).eq('name','Atlas').single();if(vault.error)throw vault.error;const profile=await client.from('atlas_profiles').select('id').eq('vault_id',vault.data.id).eq('profile_key','me').eq('kind','person').eq('owner_user_id',user.id).maybeSingle();if(profile.error)throw profile.error;if(!profile.data?.id)throw new Error('Me cloud profile is unavailable.');target={userId:user.id,profileId:profile.data.id};return target}
  async function readMeta(){if(!target)await resolveTarget();const {data,error}=await client.from('atlas_records').select('record_id,payload,revision,created_at,updated_at').eq('profile_id',target.profileId).eq('record_type',META_TYPE).eq('record_id',META_ID).maybeSingle();if(error)throw error;return data||null}
  function sharedEpoch(meta){const p=meta?.payload;return p?.schema==='atlas_entity_sync_meta'&&p?.status==='ready'&&typeof p?.canonicalEpoch==='string'&&p.canonicalEpoch?String(p.canonicalEpoch):''}
  async function readEntityRows(){if(!target)await resolveTarget();const rows=[];let from=0;while(true){const {data,error}=await client.from('atlas_records').select('record_id,payload,revision,client_updated_at,updated_at').eq('profile_id',target.profileId).eq('record_type',ENTITY_TYPE).order('record_id',{ascending:true}).range(from,from+PAGE_SIZE-1);if(error)throw error;const batch=Array.isArray(data)?data:[];rows.push(...batch);if(batch.length<PAGE_SIZE)break;from+=PAGE_SIZE}return rows}
  function entriesFromRows(rows){const out={};for(const row of rows||[]){const record=Core.recordFromPayload(row?.payload);if(!record)continue;const key=Core.keyFor(record.kind,record.id);if(row.record_id!==key)continue;out[key]={record,revision:Number(row.revision||0)}}return out}

  function baseKey(){return target?.profileId?BASE_PREFIX+target.profileId:''}
  async function readBase(){const key=baseKey();if(!key)return null;if(db&&typeof DB_STORE==='string')try{const value=await new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readonly'),req=tx.objectStore(DB_STORE).get(key);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)});if(value?.schema==='atlas_entity_sync_base'&&value.version===3&&Core.plain(value.records)&&typeof value.canonicalEpoch==='string')return value}catch(_){}try{const raw=localStorage.getItem(key),value=raw?JSON.parse(raw):null;return value?.schema==='atlas_entity_sync_base'&&value.version===3&&Core.plain(value.records)&&typeof value.canonicalEpoch==='string'?value:null}catch(_){return null}}
  async function writeBase(entries,epoch){const key=baseKey(),value={schema:'atlas_entity_sync_base',version:3,canonicalEpoch:String(epoch||''),savedAt:Date.now(),records:Core.clone(entries||{})};if(!key)return;if(db&&typeof DB_STORE==='string')try{await new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});return}catch(_){}try{localStorage.setItem(key,JSON.stringify(value))}catch(_){}}

  async function writeMutation(key,record,remoteEntry){const payload=Core.payloadFor(record,deviceId(),Date.now()),now=Date.now();if(remoteEntry){const {data,error}=await client.from('atlas_records').update({payload,client_updated_at:now,revision:Number(remoteEntry.revision||0)+1,updated_by:target.userId}).eq('profile_id',target.profileId).eq('record_type',ENTITY_TYPE).eq('record_id',key).eq('revision',Number(remoteEntry.revision||0)).select('record_id,revision');if(error)throw error;return Array.isArray(data)&&data.length===1}const {error}=await client.from('atlas_records').insert({profile_id:target.profileId,record_type:ENTITY_TYPE,record_id:key,payload,client_updated_at:now,updated_by:target.userId});if(error){if(error.code==='23505')return false;throw error}return true}
  function timeValue(item){for(const key of ['updatedAt','modifiedAt','createdAt','time','start']){const raw=item?.[key];if(raw===undefined||raw===null)continue;const n=Number(raw);if(Number.isFinite(n)&&n>0)return n;const d=Date.parse(raw);if(Number.isFinite(d))return d}return 0}
  function materialiseEntries(entries,current){const candidate=Core.clone(current),records=Object.values(entries||{}).map(entry=>entry.record).filter(Boolean);for(const kind of Core.COLLECTIONS){const active=records.filter(record=>record.kind===kind&&!record.deleted).map(record=>Core.clone(record.data));const oldOrder=new Map((Array.isArray(current?.[kind])?current[kind]:[]).map((item,index)=>[String(item?.id),index]));if(['projects','notes','daily','calendar','quickTodos','activity'].includes(kind))active.sort((a,b)=>timeValue(b)-timeValue(a)||(oldOrder.get(String(a?.id))??1e9)-(oldOrder.get(String(b?.id))??1e9));else active.sort((a,b)=>(oldOrder.get(String(a?.id))??1e9)-(oldOrder.get(String(b?.id))??1e9)||String(a?.id||'').localeCompare(String(b?.id||'')));candidate[kind]=active}const scratch={};for(const record of records)if(record.kind==='scratch'&&!record.deleted)scratch[record.id]=String(record.data??'');candidate.scratch=scratch;return candidate}
  async function applyRemote(entries,startSeq,startFingerprint,reason){if(!localStillSame(startSeq,startFingerprint))return false;const candidate=materialiseEntries(entries,state);const before=localFingerprint(),after=Core.canonical(Core.flattenState(candidate));if(before!==after&&typeof idbBackup==='function')await idbBackup(Core.clone(state),reason||'before Shared Atlas apply');if(!localStillSame(startSeq,startFingerprint))return false;state=ensureState(candidate);if(db)await idbSet(state);else try{localStorage.setItem(FALLBACK_KEY,JSON.stringify(state))}catch(_){};renderAll(false);return true}

  async function syncNow(){if(!ready||busy||!online())return;busy=true;const startSeq=localSeq,startFingerprint=localFingerprint();try{emit('SYNCING','Syncing with Shared Atlas…');const meta=await readMeta(),epoch=sharedEpoch(meta);if(!epoch){ready=false;recoveryRequired=true;emit('RECOVERY REQUIRED','Shared Atlas needs one-time recovery before cross-device sync can resume.');return}const base=await readBase(),hasMatchingBase=!!base&&base.canonicalEpoch===epoch;for(let attempt=0;attempt<4;attempt++){const remote=entriesFromRows(await readEntityRows()),local=Core.flattenState(state);const plan=hasMatchingBase?Core.reconcile(base.records||{},remote,local,true):Core.reconcile({},remote,local,false);let conflicted=false;for(const [key,record] of Object.entries(plan.mutations)){if(!localStillSame(startSeq,startFingerprint)){schedulePush(100);return}const ok=await writeMutation(key,record,remote[key]);if(!ok){conflicted=true;break}}if(conflicted)continue;const finalRemote=entriesFromRows(await readEntityRows());if(!localStillSame(startSeq,startFingerprint)){schedulePush(100);return}const reason=hasMatchingBase?'before Shared Atlas reconcile':'before Shared Atlas pull / stale-client quarantine';const applied=await applyRemote(finalRemote,startSeq,startFingerprint,reason);if(!applied){schedulePush(100);return}await writeBase(finalRemote,epoch);recoveryRequired=false;emit('SYNCED',hasMatchingBase?'Atlas synced.':'Shared Atlas loaded; this browser is now aligned.',{records:Object.keys(finalRemote).length,sharedEpoch:epoch,quarantinedStaleLocal:!hasMatchingBase});return}throw new Error('Shared Atlas changed repeatedly while syncing. Retrying shortly.')}catch(error){emit(online()?'ERROR':'OFFLINE',String(error?.message||'Shared Atlas sync failed.'));setTimeout(()=>schedulePush(1000),1600)}finally{busy=false}}
  function schedulePush(delay=450){if(!ready)return;clearTimeout(pushTimer);pushTimer=setTimeout(syncNow,delay)}
  function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(()=>{if(document.visibilityState!=='hidden')syncNow()},5000)}
  async function initAfterLocalLoad(){if(loaded)return;loaded=true;if(!online())return emit('OFFLINE','Atlas is using its offline cache. Shared Atlas sync will resume automatically when online.');try{await resolveTarget();const meta=await readMeta(),epoch=sharedEpoch(meta);if(!epoch){ready=false;recoveryRequired=true;emit('RECOVERY REQUIRED','Shared Atlas needs one-time recovery before cross-device sync resumes.');return}ready=true;recoveryRequired=false;await syncNow();startPolling()}catch(error){ready=false;emit('LOCAL',String(error?.message||'Sign in to Atlas cloud to sync.'))}}
  async function retryAfterRecovery(){loaded=false;ready=false;recoveryRequired=false;await initAfterLocalLoad()}

  const originalSave=save,originalLoad=load;
  save=async function(){const result=await originalSave.apply(this,arguments);localSeq++;if(ready){emit('PENDING','Changes are waiting to sync to Shared Atlas.');schedulePush()}return result};
  load=async function(){const result=await originalLoad.apply(this,arguments);await initAfterLocalLoad();return result};
  root.addEventListener?.('focus',()=>{if(ready)syncNow();else if(recoveryRequired)retryAfterRecovery()});
  root.addEventListener?.('online',()=>{if(!loaded||!ready)retryAfterRecovery();else syncNow()});
  document.addEventListener?.('visibilitychange',()=>{if(document.visibilityState==='visible'){if(ready)syncNow();else if(recoveryRequired)retryAfterRecovery()}});
  root.addEventListener?.('atlascloudstatus',event=>{if(event.detail?.authenticated&&!ready&&!recoveryRequired){loaded=false;initAfterLocalLoad()}});
  root.addEventListener?.('atlascanonicalrecovered',()=>retryAfterRecovery());
  root.AtlasCloudSync=Object.freeze({initAfterLocalLoad,refreshNow:syncNow,pushNow:syncNow,retryAfterRecovery,migrateSharedCloud:async()=>false,getStatus:()=>({ready,joined:ready,dirty:lastMessage.includes('waiting'),recordLevel:true,recoveryRequired,target:target?{profileId:target.profileId}:null})});
})(window);
