// Editors, overlays, menus, capture/search and shared event wiring.
function openProject(id){const p=projectById(id);if(!p)return;activeProjectId=id;document.getElementById('projectCode').textContent=`${p.code} / ${p.status}`;document.getElementById('projectTitle').textContent=p.title;document.getElementById('projectBody').innerHTML=`<div class="form"><div class="row2"><div><div class="code">OBJECTIVE</div><p style="font-size:12px;line-height:1.5">${esc(p.objective)}</p></div><div><div class="code">NEXT MOVE</div><p style="font-size:12px;line-height:1.5">${esc(p.next)}</p></div></div><div><div class="code">MILESTONES</div>${milestonesHtmlForProject(p)}</div><div><div class="code">TASKS</div><div class="mini-list">${(p.tasks||[]).map(t=>`<label class="mini-row"><input type="checkbox" data-project-task="${t.id}" ${t.done?'checked':''}/><span>${esc(t.title)}</span><span class="badge">${t.done?'DONE':'OPEN'}</span></label>`).join('')}</div></div><div class="tags">${(p.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div>`;openOverlay('projectOverlay')}
function milestonesHtmlForProject(p){return `<div class="milestones" style="padding-left:0;padding-right:0">${(p.milestones||[]).map(m=>`<label class="mrow"><input type="checkbox" data-project-milestone="${m.id}" ${m.done?'checked':''} style="accent-color:var(--green)"/><div><div class="mname">${esc(m.title)}</div><div class="mmeta">${m.current?'CURRENT':''}</div></div><span class="badge">${m.done?'DONE':m.current?'CURRENT':'OPEN'}</span></label>`).join('')}</div>`}

function openCapture(type='note',areaId=''){document.getElementById('capType').value=type;populateAreaSelect(document.getElementById('capArea'),areaId);document.getElementById('capTitle').value='';document.getElementById('capBody').value='';document.getElementById('capTags').value='';document.getElementById('capMap').value='false';const hint=document.getElementById('capProfileHint');if(hint)hint.textContent=`PROFILE / ${activeProfile().name}`;openOverlay('captureOverlay');setTimeout(()=>document.getElementById('capTitle').focus(),80)}
function populateAreaSelect(sel,value=''){const opts=profileAreas().filter(a=>a.level>=2&&spaceAllows(a.space)).sort((a,b)=>a.name.localeCompare(b.name));sel.innerHTML=`<option value="">Inbox / unlinked</option>`+opts.map(a=>`<option value="${a.id}" ${a.id===value?'selected':''}>${esc(a.name)} · ${esc(a.code)}</option>`).join('')}
function saveCapture(){const type=document.getElementById('capType').value,areaId=document.getElementById('capArea').value,title=document.getElementById('capTitle').value.trim(),body=document.getElementById('capBody').value.trim(),tags=document.getElementById('capTags').value.split(',').map(s=>s.trim()).filter(Boolean),show=document.getElementById('capMap').value==='true';if(!title&&!body)return toast('Add some content first');const area=areaById(areaId);const space=area?.space||(state.settings.spaceFilter==='work'?'work':'personal');const profile=state.settings.activeProfile||'me';if(type==='project'){const p={id:uid('p'),profile,space,areaId:areaId||'',topicId:'',code:`P-${String(state.projects.length+1).padStart(2,'0')}`,title:title||'New Project',status:'ACTIVE',objective:body,next:'',tags,createdAt:now(),milestones:[],tasks:[]};state.projects.unshift(p);log(`Project created: ${p.title}.`)}else if(type==='task'){let p=visibleProjects(areaId)[0];if(p){p.tasks.push({id:uid('t'),title:title||body,done:false});log(`Task added to ${p.title}: ${title||body}.`)}else{state.notes.unshift({id:uid('n'),profile,space,areaId:areaId||'',topicId:'',type:'task',title:title||'Task',body,tags,createdAt:now(),showOnMap:show});log(`Unassigned task captured: ${title}.`)}}else if(type==='daily'){state.daily.unshift({id:uid('d'),profile,date:todayKey(),createdAt:now(),text:[title,body].filter(Boolean).join(' — '),areaId});log('Daily entry captured.')}else{state.notes.unshift({id:uid('n'),profile,space,areaId:areaId||'',topicId:area?.level>=4?area.id:'',type,title:title||body.slice(0,70)||'Untitled',body,tags,createdAt:now(),showOnMap:show});log(`${type} captured: ${title||'Untitled'}.`)}save();closeOverlay('captureOverlay');renderAll();toast(`Saved to ${activeProfile().name}`)}

function search(q){q=q.trim().toLowerCase();if(!q)return[];const res=[];profileAreas().forEach(a=>{if([a.name,a.code,a.description].join(' ').toLowerCase().includes(q))res.push({kind:'AREA',title:a.name,meta:a.description,id:a.id})});state.projects.filter(p=>profileAllows(p.profile)).forEach(p=>{if([p.title,p.code,p.objective,p.next,...(p.tags||[])].join(' ').toLowerCase().includes(q))res.push({kind:'PROJECT',title:p.title,meta:p.next,id:p.id})});state.notes.filter(n=>profileAllows(n.profile)).forEach(n=>{if([n.title,n.body,...(n.tags||[])].join(' ').toLowerCase().includes(q))res.push({kind:'NOTE',title:n.title,meta:n.body,id:n.id,areaId:n.areaId})});return res.slice(0,30)}
function renderSearch(){const q=document.getElementById('searchInput').value;const r=search(q);document.getElementById('searchResults').innerHTML=q?`<div class="notes-list">${r.length?r.map(x=>`<div class="note clickable" data-search-kind="${x.kind}" data-search-id="${x.id}" data-search-area="${x.areaId||''}"><div class="note-top"><strong class="note-title">${esc(x.title)}</strong><span class="note-type">${x.kind}</span></div><div class="note-body">${esc(String(x.meta||'').slice(0,180))}</div></div>`).join(''):'<div class="empty">No matches.</div>'}</div>`:'<div class="empty">Search projects, notes, topics, codes or tags.</div>'}

const editorTabs=[['structure','Structure'],['profiles','Profiles'],['projects','Projects'],['notes','Notes'],['links','Connections'],['security','Security'],['data','Data / Reset']];
function openEditor(){renderEditor();openOverlay('editorOverlay')}
function renderEditor(){document.getElementById('editorNav').innerHTML=editorTabs.map(([id,n])=>`<button class="btn ${state.settings.editorTab===id?'primary':''}" data-editor-tab="${id}">${n}</button>`).join('');const e=document.getElementById('editorPane');if(state.settings.editorTab==='structure')e.innerHTML=editorStructure();if(state.settings.editorTab==='profiles')e.innerHTML=editorProfiles();if(state.settings.editorTab==='projects')e.innerHTML=editorProjects();if(state.settings.editorTab==='notes')e.innerHTML=editorNotes();if(state.settings.editorTab==='links')e.innerHTML=editorLinks();if(state.settings.editorTab==='security')e.innerHTML=editorSecurity();if(state.settings.editorTab==='data')e.innerHTML=editorData()}
function field(label,html){return `<div class="field"><label>${label}</label>${html}</div>`}

function editorProfiles(){return `<section class="editor-section"><div class="editor-section-head"><h4>Household Profiles</h4><span class="code">LOCAL PROFILE CONTEXTS</span></div><div class="editor-section-body"><div class="profile-grid">${state.profiles.map((p,i)=>`<div class="profile-card"><div class="profile-glyph">${esc(p.id==='alyssa'?'ALY':p.id==='us'?'US':'ME')}</div>${field('Name',`<input data-profile-edit="${i}" value="${esc(p.name)}">`)}<p>${p.kind==='shared'?'Shared household context. Entangled calendar events land here.':'Personal context. Notes, projects, daily entries and calendar events stay in this profile unless explicitly shared.'}</p></div>`).join('')}</div><p class="code" style="margin-top:12px">Profiles are isolated Atlas contexts inside one locally locked household shell. Switching profile changes the graph, notes, projects, daily data, calendar and activity. Only deliberate Entangle actions cross into Us.</p></div></section>`}
function editorStructure(){const items=profileAreas();return `<section class="editor-section"><div class="editor-section-head"><h4>${esc(activeProfile().name)} · Areas / Topics</h4><button class="btn small primary" data-ed-action="add-area">+ Add</button></div><div class="editor-section-body"><div class="table-list">${items.map(a=>{const i=state.areas.indexOf(a);return `<div class="edit-row"><div>${field('Name',`<input data-area-edit="${i}" data-field="name" value="${esc(a.name)}">`)}</div><div>${field('Level',`<select data-area-edit="${i}" data-field="level">${[2,3,4].map(v=>`<option value="${v}" ${a.level===v?'selected':''}>${v}</option>`).join('')}</select>`)}</div><div>${field('Parent',`<select data-area-edit="${i}" data-field="parentId"><option value="atlas">ATLAS</option>${items.filter(x=>x.id!==a.id&&x.level<a.level).map(x=>`<option value="${x.id}" ${a.parentId===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select>`)}</div><div class="inline-actions"><button class="btn small" data-ed-action="edit-area" data-index="${i}">Detail</button><button class="btn small danger" data-ed-action="remove-area" data-index="${i}">×</button></div></div>`}).join('')}</div></div></section><div class="code">Each profile owns a separate constellation. Reform recalculates only ${esc(activeProfile().name)}.</div>`}
function editorProjects(){const items=state.projects.filter(p=>profileAllows(p.profile)),areas=profileAreas();return `<section class="editor-section"><div class="editor-section-head"><h4>${esc(activeProfile().name)} · Projects</h4><button class="btn small primary" data-ed-action="add-project">+ Project</button></div><div class="editor-section-body"><div class="table-list">${items.map(p=>{const i=state.projects.indexOf(p);return `<div class="edit-row project-row"><div>${field('Title',`<input data-proj-edit="${i}" data-field="title" value="${esc(p.title)}">`)}</div><div>${field('Status',`<select data-proj-edit="${i}" data-field="status">${['ACTIVE','WATCHING','PAUSED','COMPLETE'].map(v=>`<option ${p.status===v?'selected':''}>${v}</option>`).join('')}</select>`)}</div><div>${field('Area',`<select data-proj-edit="${i}" data-field="areaId"><option value="">Unlinked</option>${areas.map(a=>`<option value="${a.id}" ${p.areaId===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select>`)}</div><div class="inline-actions"><button class="btn small" data-ed-action="edit-project" data-index="${i}">Detail</button><button class="btn small danger" data-ed-action="remove-project" data-index="${i}">×</button></div></div>`}).join('')}</div></div></section>`}
function editorNotes(){const items=state.notes.filter(n=>profileAllows(n.profile)),areas=profileAreas();return `<section class="editor-section"><div class="editor-section-head"><h4>${esc(activeProfile().name)} · Notes</h4><button class="btn small primary" data-ed-action="add-note">+ Note</button></div><div class="editor-section-body"><div class="table-list">${items.map(n=>{const i=state.notes.indexOf(n);return `<div class="edit-row note-row"><div>${field('Title',`<input data-note-edit="${i}" data-field="title" value="${esc(n.title)}">`)}</div><div>${field('Type',`<input data-note-edit="${i}" data-field="type" value="${esc(n.type)}">`)}</div><div>${field('Area',`<select data-note-edit="${i}" data-field="areaId"><option value="">Inbox</option>${areas.map(a=>`<option value="${a.id}" ${n.areaId===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select>`)}</div><div class="inline-actions"><button class="btn small" data-ed-action="edit-note" data-index="${i}">Detail</button><button class="btn small danger" data-ed-action="remove-note" data-index="${i}">×</button></div></div>`}).join('')}</div></div></section>`}
function editorLinks(){const items=profileLinks(),areas=profileAreas();return `<section class="editor-section"><div class="editor-section-head"><h4>${esc(activeProfile().name)} · Cross-connections</h4><button class="btn small primary" data-ed-action="add-link">+ Connection</button></div><div class="editor-section-body"><div class="table-list">${items.map(l=>{const i=state.links.indexOf(l);return `<div class="edit-row"><div>${field('From',`<select data-link-edit="${i}" data-field="source">${areas.map(a=>`<option value="${a.id}" ${l.source===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select>`)}</div><div>${field('To',`<select data-link-edit="${i}" data-field="target">${areas.map(a=>`<option value="${a.id}" ${l.target===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select>`)}</div><div>${field('Type',`<select data-link-edit="${i}" data-field="type"><option value="cross">Cross-link</option></select>`)}</div><button class="btn small danger" data-ed-action="remove-link" data-index="${i}">Remove</button></div>`}).join('')}</div></div></section>`}
function editorSecurity(){if(authConfig?.enabled===false)return `<section class="editor-section"><div class="editor-section-head"><h4>Atlas Lock</h4><span class="code">DISABLED</span></div><div class="editor-section-body"><p style="font-size:11px;line-height:1.5;color:var(--muted)">Atlas Lock is disabled on this device.</p><div class="inline-actions"><button class="btn primary" data-ed-action="enable-lock">Enable Atlas Lock</button></div></div></section>`;const idle=Number(authConfig?.idleMinutes??15);return `<section class="editor-section"><div class="editor-section-head"><h4>Atlas Lock</h4><span class="code">4-DIGIT PIN</span></div><div class="editor-section-body"><p style="font-size:11px;line-height:1.5;color:var(--muted)">Local device lock. The PIN verifier is stored separately from Atlas content and is not included in exports.</p>${recoveryAuthenticated?'<p style="font-size:10px;line-height:1.5;color:var(--amber);margin:0 0 10px">Recovery access active.</p>':''}<div class="row2">${field('Auto-lock',`<select id="secIdle"><option value="5" ${idle===5?'selected':''}>5 minutes</option><option value="15" ${idle===15?'selected':''}>15 minutes</option><option value="30" ${idle===30?'selected':''}>30 minutes</option><option value="60" ${idle===60?'selected':''}>1 hour</option><option value="0" ${idle===0?'selected':''}>Never</option></select>`)}${field('Current PIN',`<input id="secCurrent" type="password" inputmode="numeric" maxlength="4" autocomplete="current-password" placeholder="${recoveryAuthenticated?'Recovery active':'••••'}" ${recoveryAuthenticated?'disabled':''}>`)}</div><div class="row2">${field('New PIN',`<input id="secNew" type="password" inputmode="numeric" maxlength="4" autocomplete="new-password" placeholder="4 digits">`)}${field('Confirm PIN',`<input id="secConfirm" type="password" inputmode="numeric" maxlength="4" autocomplete="new-password" placeholder="4 digits">`)}</div><div class="inline-actions"><button class="btn primary" data-ed-action="save-security">Save Auto-lock</button><button class="btn" data-ed-action="change-password">Change PIN</button><button class="btn" data-ed-action="new-recovery">New Recovery Key</button><button class="btn danger" data-ed-action="disable-lock">Disable Lock</button></div><p id="securityMessage" style="font:750 9px/1.5 SFMono-Regular,Consolas,monospace;color:var(--amber);margin-top:11px"></p><p style="font-size:10px;line-height:1.5;color:var(--muted);margin-top:12px">This is an interface lock; encrypted-at-rest storage remains a separate future migration.</p></div></section>`}
async function verifyCurrentSecurityPassword(){if(recoveryAuthenticated)return true;const el=document.getElementById('secCurrent');const p=(el?.value||'').replace(/\D/g,'').slice(0,4);if(!/^\d{4}$/.test(p))return false;try{const verifier=authConfig.pin||authConfig.password;const v=await deriveVerifier(p,verifier.salt,verifier.iterations);return safeEqual(v,verifier.verifier)}catch(_){return false}}
function editorData(){const saved=state.meta?.lastSavedAt?`${fmtDate(state.meta.lastSavedAt)} · ${fmtTime(state.meta.lastSavedAt)}`:'—';return `<section class="editor-section"><div class="editor-section-head"><h4>Data</h4><span class="code">APP ${APP_VERSION} · DATA v${DATA_VERSION}</span></div><div class="editor-section-body"><p style="font-size:11px;line-height:1.5;color:var(--muted)">Atlas keeps your records separate from the interface code. On a fixed hosted Atlas URL, application updates reuse the same IndexedDB database and create an automatic snapshot before a new app/data version is applied.</p><div class="meta" style="margin:8px 0 12px">Last saved ${saved}</div><div class="inline-actions"><button class="btn" data-ed-action="snapshot">Create Snapshot</button><button class="btn" data-ed-action="restore-latest">Restore Latest Snapshot</button><button class="btn" data-ed-action="export">Export JSON</button><button class="btn danger" data-ed-action="reset">Reset Demo Data</button></div><p style="font-size:10px;line-height:1.5;color:var(--muted);margin-top:12px">Local downloaded <code>file://</code> copies are not a reliable update channel because browsers may treat different local file locations as different storage origins. Until Atlas is hosted at one stable URL, export JSON before replacing the local file.</p></div></section>`}
function openAreaEditor(i){const a=state.areas[i];if(!a||!profileAllows(a.profile))return;const areas=profileAreas();document.getElementById('editorPane').innerHTML=`<button class="btn small" data-ed-action="back-structure">← Structure</button><section class="editor-section" style="margin-top:9px"><div class="editor-section-head"><h4>${esc(a.code)} · Area Detail</h4><span class="code">${esc(activeProfile().name)}</span></div><div class="editor-section-body"><div class="project-editor"><div class="row3">${field('Name',`<input id="eaName" value="${esc(a.name)}">`)}${field('Map code · auto',`<input id="eaCode" value="${esc(a.code)}" readonly title="Generated from the node name · 3–5 characters">`)}${field('Space',`<select id="eaSpace"><option value="work" ${a.space==='work'?'selected':''}>Work</option><option value="personal" ${a.space==='personal'?'selected':''}>Personal</option></select>`)}</div><div class="row2">${field('Level',`<select id="eaLevel">${[2,3,4].map(v=>`<option value="${v}" ${a.level===v?'selected':''}>${v}</option>`).join('')}</select>`)}${field('Parent',`<select id="eaParent"><option value="atlas">ATLAS</option>${areas.filter(x=>x.id!==a.id&&x.level<a.level).map(x=>`<option value="${x.id}" ${a.parentId===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select>`)}</div>${field('Description',`<textarea id="eaDescription">${esc(a.description||'')}</textarea>`)}<button class="btn primary" data-ed-action="save-area-detail" data-index="${i}">Save Area</button></div></div></section>`}
function openNoteEditor(i){const n=state.notes[i];if(!n||!profileAllows(n.profile))return;const areas=profileAreas();document.getElementById('editorPane').innerHTML=`<button class="btn small" data-ed-action="back-notes">← Notes</button><section class="editor-section" style="margin-top:9px"><div class="editor-section-head"><h4>Note Detail</h4><span class="code">${esc(activeProfile().name)}</span></div><div class="editor-section-body"><div class="project-editor"><div class="row2">${field('Title',`<input id="enTitle" value="${esc(n.title)}">`)}${field('Type',`<input id="enType" value="${esc(n.type)}">`)}</div><div class="row2">${field('Area',`<select id="enArea"><option value="">Inbox</option>${areas.map(a=>`<option value="${a.id}" ${n.areaId===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select>`)}${field('Topic',`<select id="enTopic"><option value="">None</option>${areas.filter(a=>a.level>=3).map(a=>`<option value="${a.id}" ${n.topicId===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select>`)}</div>${field('Body',`<textarea id="enBody" style="min-height:180px">${esc(n.body||'')}</textarea>`)}<div class="row2">${field('Tags',`<input id="enTags" value="${esc((n.tags||[]).join(', '))}">`)}${field('Map',`<select id="enMap"><option value="false" ${!n.showOnMap?'selected':''}>Keep off map</option><option value="true" ${n.showOnMap?'selected':''}>Show as level 5 node</option></select>`)}</div><button class="btn primary" data-ed-action="save-note-detail" data-index="${i}">Save Note</button></div></div></section>`}
function openProjectEditor(i){const p=state.projects[i];if(!p||!profileAllows(p.profile))return;document.getElementById('editorPane').innerHTML=`<button class="btn small" data-ed-action="back-projects">← Projects</button><section class="editor-section" style="margin-top:9px"><div class="editor-section-head"><h4>${esc(p.code)} · Project Detail</h4><span class="code">${esc(activeProfile().name)}</span></div><div class="editor-section-body"><div class="project-editor"><div class="row2">${field('Title',`<input id="epTitle" value="${esc(p.title)}">`)}${field('Status',`<select id="epStatus">${['ACTIVE','WATCHING','PAUSED','COMPLETE'].map(v=>`<option ${p.status===v?'selected':''}>${v}</option>`).join('')}</select>`)}</div>${field('Objective',`<textarea id="epObjective">${esc(p.objective)}</textarea>`)}${field('Next move',`<textarea id="epNext">${esc(p.next)}</textarea>`)}${field('Tags',`<input id="epTags" value="${esc((p.tags||[]).join(', '))}">`)}<div><div class="editor-section-head" style="padding-left:0;padding-right:0"><h4>Milestones</h4><button class="btn small" data-ed-action="add-milestone" data-index="${i}">+ Milestone</button></div><div class="mini-list">${(p.milestones||[]).map((m,mi)=>`<div class="mini-row"><input type="checkbox" data-ep-milestone="${mi}" ${m.done?'checked':''}><input type="text" data-ep-milestone-title="${mi}" value="${esc(m.title)}"><button class="btn small danger" data-ed-action="remove-milestone" data-index="${i}" data-subindex="${mi}">×</button></div>`).join('')}</div></div><div><div class="editor-section-head" style="padding-left:0;padding-right:0"><h4>Tasks</h4><button class="btn small" data-ed-action="add-task" data-index="${i}">+ Task</button></div><div class="mini-list">${(p.tasks||[]).map((t,ti)=>`<div class="mini-row"><input type="checkbox" data-ep-task="${ti}" ${t.done?'checked':''}><input type="text" data-ep-task-title="${ti}" value="${esc(t.title)}"><button class="btn small danger" data-ed-action="remove-task" data-index="${i}" data-subindex="${ti}">×</button></div>`).join('')}</div></div><button class="btn primary" data-ed-action="save-project-detail" data-index="${i}">Save Project</button></div></div></section>`}

function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`atlas-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(url)}
function openOverlay(id){document.getElementById(id).classList.add('open')} function closeOverlay(id){document.getElementById(id).classList.remove('open')}

// Global click handling
document.addEventListener('click',e=>{
  const close=e.target.closest('[data-close]');if(close){closeOverlay(close.dataset.close);return}
  const mt=e.target.closest('[data-main-tab]');if(mt){state.settings.activeTab=mt.dataset.mainTab;state.settings.selectedArea=['home','daily','inbox'].includes(mt.dataset.mainTab)?'':mt.dataset.mainTab;state.settings.subtab='overview';renderAll();return}
  const st=e.target.closest('[data-subtab]');if(st){state.settings.subtab=st.dataset.subtab;renderArea(state.settings.selectedArea||state.settings.activeTab);save();return}
  const oa=e.target.closest('[data-open-area]');if(oa){const a=areaById(oa.dataset.openArea);if(a&&areaAllows(a)){state.settings.activeTab=getTopDomain(a)?.id||a.id;state.settings.selectedArea=a.id;state.settings.subtab='overview';renderTabs();renderArea(a.id);save()}return}
  const pc=e.target.closest('[data-project]');if(pc){openProject(pc.dataset.project);return}
  const qa=e.target.closest('[data-quick-add]');if(qa){openCapture(qa.dataset.quickAdd,qa.dataset.area||'');return}
  const ce=e.target.closest('[data-calendar-event]');if(ce){openCalendarEvent(ce.dataset.calendarEvent);return}
  const ca=e.target.closest('[data-cal-add]');if(ca){openCalendarEvent('',ca.dataset.calAdd);return}
  const cn=e.target.closest('[data-cal-nav]');if(cn){let d=monthCursorDate();if(cn.dataset.calNav==='today')d=new Date();else d.setMonth(d.getMonth()+(cn.dataset.calNav==='next'?1:-1));setCalendarCursor(new Date(d.getFullYear(),d.getMonth(),1));save();renderCalendar();return}
  const sk=e.target.closest('[data-search-kind]');if(sk){closeOverlay('searchOverlay');if(sk.dataset.searchKind==='PROJECT')openProject(sk.dataset.searchId);else if(sk.dataset.searchKind==='AREA'){const a=areaById(sk.dataset.searchId);if(a&&areaAllows(a)){state.settings.activeTab=getTopDomain(a)?.id||a.id;state.settings.selectedArea=a.id;state.settings.subtab='overview';renderTabs();renderArea(a.id);save()}}else if(sk.dataset.searchArea){const a=areaById(sk.dataset.searchArea);if(a&&areaAllows(a)){state.settings.activeTab=getTopDomain(a)?.id||a.id;state.settings.selectedArea=a.id;state.settings.subtab='notes';renderTabs();renderArea(a.id);save()}}return}
  const et=e.target.closest('[data-editor-tab]');if(et){state.settings.editorTab=et.dataset.editorTab;renderEditor();save();return}
  const act=e.target.closest('[data-ed-action]');if(act)handleEditorAction(act)
});
document.getElementById('utilityRail').addEventListener('click',e=>{const b=e.target.closest('[data-side-tab]');if(b){setUtilityPane(b.dataset.sideTab);const d=b.closest('details');if(d)d.removeAttribute('open')}});
document.getElementById('utilityPane').addEventListener('input',e=>{if(e.target.id==='scratchArea'){state.scratch[state.settings.activeProfile||'me']=e.target.value;save()}});
document.getElementById('utilityPane').addEventListener('keydown',e=>{if(e.target.id==='quickTodoInput'&&e.key==='Enter'){e.preventDefault();addQuickTodo()}});
document.getElementById('utilityPane').addEventListener('change',e=>{if(e.target.dataset.quickTodo){const t=(state.quickTodos||[]).find(x=>x.id===e.target.dataset.quickTodo);if(t){t.done=e.target.checked;save();renderUtilityPane()}}});
document.getElementById('utilityPane').addEventListener('click',e=>{
  const cal=e.target.closest('[data-calendar-id]');if(cal){openCalendarEvent(cal.dataset.calendarId);return}
  const b=e.target.closest('[data-side-action]');if(!b)return;const a=b.dataset.sideAction;
  if(a==='close'){state.settings.sidePane='';save();renderUtilityPane();return}
  if(a==='dock'){
    const dock=b.dataset.dock||'top';state.settings.toolPaneDock=dock;state.settings.toolPaneFloating=dock==='float';
    if(dock==='float'&&!state.settings.toolPaneX){state.settings.toolPaneX=Math.max(12,window.innerWidth-390);state.settings.toolPaneY=78}
    save();renderUtilityPane();requestAnimationFrame(()=>{if(state.settings.activeTab==='home'){mapCamera('home').needsFit=true;drawNetwork(null)}});return
  }
  if(a==='add-todo')addQuickTodo();
  if(a==='delete-todo'){state.quickTodos=state.quickTodos.filter(t=>t.id!==b.dataset.id);save();renderUtilityPane()}
  if(a==='clear-done'){state.quickTodos=state.quickTodos.filter(t=>(t.profile||'me')!==(state.settings.activeProfile||'me')||!t.done);save();renderUtilityPane()}
  if(a==='commit-scratch')commitScratch();
  if(a==='clear-scratch'){state.scratch[state.settings.activeProfile||'me']='';save();renderUtilityPane()}
});

let toolDrag=null;
document.getElementById('utilityPane').addEventListener('pointerdown',e=>{
  const head=e.target.closest('[data-tool-drag]');if(!head||e.target.closest('button,summary,details'))return;
  const pane=document.getElementById('utilityPane'),rect=pane.getBoundingClientRect();
  if((state.settings.toolPaneDock||'top')!=='float'){
    state.settings.toolPaneDock='float';state.settings.toolPaneFloating=true;
    state.settings.toolPaneX=Math.max(8,Math.min(window.innerWidth-368,e.clientX-180));state.settings.toolPaneY=Math.max(62,rect.top);
    applyToolPanePlacement();
    const mode=pane.querySelector('.tool-dock-menu>summary');if(mode)mode.textContent='Dock';
  }
  const r=pane.getBoundingClientRect();
  toolDrag={pointerId:e.pointerId,dx:e.clientX-r.left,dy:e.clientY-r.top};
  document.body.classList.add('tool-dragging');document.body.dataset.snapTarget='';
  try{pane.setPointerCapture(e.pointerId)}catch(_){}
  e.preventDefault();
});
document.addEventListener('pointermove',e=>{
  if(!toolDrag)return;const pane=document.getElementById('utilityPane'),w=pane?.getBoundingClientRect().width||360,h=pane?.getBoundingClientRect().height||300;
  state.settings.toolPaneX=Math.max(8,Math.min(window.innerWidth-w-8,e.clientX-toolDrag.dx));
  state.settings.toolPaneY=Math.max(62,Math.min(window.innerHeight-Math.min(h,130),e.clientY-toolDrag.dy));
  let snap='';if(e.clientY<118)snap='top';else if(e.clientX<72)snap='left';else if(e.clientX>window.innerWidth-72)snap='right';
  document.body.dataset.snapTarget=snap;applyToolPanePlacement();
});
document.addEventListener('pointerup',e=>{
  if(!toolDrag)return;const pane=document.getElementById('utilityPane'),snap=document.body.dataset.snapTarget||'';
  try{pane?.releasePointerCapture(toolDrag.pointerId)}catch(_){}
  toolDrag=null;document.body.classList.remove('tool-dragging');document.body.dataset.snapTarget='';
  if(snap){state.settings.toolPaneDock=snap;state.settings.toolPaneFloating=false;state.settings.toolPaneX=0;state.settings.toolPaneY=0}
  save();renderUtilityPane();requestAnimationFrame(()=>{if(state.settings.activeTab==='home'){mapCamera('home').needsFit=true;drawNetwork(null)}});
});
window.addEventListener('resize',()=>{if(state?.settings?.sidePane){const cam=mapCamera('home');cam.needsFit=true;applyToolPanePlacement();if(state.settings.activeTab==='home')requestAnimationFrame(()=>drawNetwork(null))}});


document.getElementById('profileMenuPanel').addEventListener('click',e=>{const b=e.target.closest('[data-profile-id]');if(!b)return;const s=document.getElementById('profileSelect');s.value=b.dataset.profileId;s.dispatchEvent(new Event('change',{bubbles:true}))});
document.getElementById('viewMenuPanel').addEventListener('click',e=>{const b=e.target.closest('[data-view-id]');if(!b)return;const s=document.getElementById('sectionSelect');s.value=b.dataset.viewId||'';s.dispatchEvent(new Event('change',{bubbles:true}))});
document.getElementById('spaceMenuPanel').addEventListener('click',e=>{const b=e.target.closest('[data-space-id]');if(!b)return;const s=document.getElementById('spaceFilter');s.value=b.dataset.spaceId||'all';s.dispatchEvent(new Event('change',{bubbles:true}))});

const atlasMenus=[...document.querySelectorAll('.system-menu')];
atlasMenus.forEach(menu=>menu.addEventListener('toggle',()=>{if(menu.open)atlasMenus.forEach(other=>{if(other!==menu)other.removeAttribute('open')})}));
document.addEventListener('pointerdown',e=>{atlasMenus.forEach(menu=>{if(menu.open&&!menu.contains(e.target))menu.removeAttribute('open')})});
document.addEventListener('click',e=>{if(e.target.closest('.system-item'))atlasMenus.forEach(menu=>menu.removeAttribute('open'))});
document.getElementById('homeBtn').addEventListener('click',()=>{state.settings.activeTab='home';state.settings.selectedArea='';state.settings.subtab='overview';renderAll()});document.getElementById('captureBtn').addEventListener('click',()=>openCapture());document.getElementById('searchBtn').addEventListener('click',()=>{openOverlay('searchOverlay');renderSearch();setTimeout(()=>document.getElementById('searchInput').focus(),80)});document.getElementById('editBtn').addEventListener('click',openEditor);document.getElementById('themeBtn').addEventListener('click',()=>{state.settings.theme=state.settings.theme==='night'?'day':'night';applyTheme();save()});document.getElementById('lockBtn').addEventListener('click',()=>lockAtlas('manual'));document.getElementById('saveCapture').addEventListener('click',saveCapture);document.getElementById('searchInput').addEventListener('input',renderSearch);document.getElementById('exportBtn').addEventListener('click',exportData);
document.getElementById('profileSelect').addEventListener('change',e=>{state.settings.activeProfile=e.target.value;state.settings.activeTab='home';state.settings.selectedArea='';state.settings.subtab='overview';state.settings.spaceFilter='all';mapCamera('home').needsFit=true;renderAll();toast(`Switched to ${activeProfile().name}`)});
document.getElementById('sectionSelect').addEventListener('change',e=>{const tab=e.target.value;if(!tab){state.settings.activeTab='home';state.settings.selectedArea='';state.settings.subtab='overview';renderAll();return}state.settings.activeTab=tab;state.settings.selectedArea=['daily','calendar','inbox'].includes(tab)?'':tab;state.settings.subtab='overview';renderAll()});
document.getElementById('spaceFilter').addEventListener('change',e=>{state.settings.spaceFilter=e.target.value;renderAll()});
document.getElementById('saveCalendarEvent').addEventListener('click',saveCalendarEvent);document.getElementById('deleteCalendarEvent').addEventListener('click',deleteCalendarEvent);
document.getElementById('projectBody').addEventListener('change',e=>{const p=projectById(activeProjectId);if(!p)return;if(e.target.dataset.projectTask){const t=p.tasks.find(x=>x.id===e.target.dataset.projectTask);if(t)t.done=e.target.checked}if(e.target.dataset.projectMilestone){const m=p.milestones.find(x=>x.id===e.target.dataset.projectMilestone);if(m)m.done=e.target.checked}log(`Project progress updated: ${p.title}.`);save();openProject(p.id);renderAll()});
document.getElementById('importFile').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{await idbBackup(state,'before JSON import');state=ensureState(JSON.parse(r.result));log('Atlas data imported.');await save();renderAll();toast('Atlas data imported')}catch(err){alert('That file could not be imported.')}};r.readAsText(f);e.target.value=''})

document.getElementById('editorPane').addEventListener('change',e=>{
  let t=e.target;
  if(t.dataset.profileEdit!==undefined){const p=state.profiles[Number(t.dataset.profileEdit)];if(p){p.name=t.value.trim()||p.name;save();renderTabs()}return}
  if(t.dataset.areaEdit!==undefined){let a=state.areas[Number(t.dataset.areaEdit)];if(a){a[t.dataset.field]=t.dataset.field==='level'?Number(t.value):t.value;if(t.dataset.field==='name')a.code=makeNodeCode(a.name);if(t.dataset.field==='level'||t.dataset.field==='parentId')organiseSphericalLayout(state,state.settings.activeProfile||'me');save();renderAll()}return}
  if(t.dataset.projEdit!==undefined){let p=state.projects[Number(t.dataset.projEdit)];if(p){p[t.dataset.field]=t.value;const ar=areaById(p.areaId);if(ar)p.space=ar.space;save();renderAll()}return}
  if(t.dataset.noteEdit!==undefined){let n=state.notes[Number(t.dataset.noteEdit)];if(n){n[t.dataset.field]=t.value;const ar=areaById(n.areaId);if(ar)n.space=ar.space;save();renderAll()}return}
  if(t.dataset.linkEdit!==undefined){let l=state.links[Number(t.dataset.linkEdit)];if(l){l[t.dataset.field]=t.value;save();renderAll()}return}
});
async function handleEditorAction(b){const a=b.dataset.edAction;
  if(a==='add-area'){const parent=profileAreas().find(x=>x.level===2)||null;state.areas.push({id:uid('area'),profile:state.settings.activeProfile||'me',name:'New Area',code:'NEW',space:parent?.space||'personal',level:parent?3:2,parentId:parent?.id||'atlas',description:'',x:600,y:340,mapZ:0,status:'default'});organiseSphericalLayout(state,state.settings.activeProfile||'me');log('New Atlas area created.');save();renderEditor();renderAll()}
  if(a==='remove-area'){const i=Number(b.dataset.index),x=state.areas[i];if(x&&confirm(`Remove ${x.name}? Linked notes/projects will become unlinked.`)){state.projects.forEach(p=>{if(p.areaId===x.id)p.areaId='';if(p.topicId===x.id)p.topicId=''});state.notes.forEach(n=>{if(n.areaId===x.id)n.areaId='';if(n.topicId===x.id)n.topicId=''});state.areas.forEach(c=>{if(c.parentId===x.id)c.parentId='atlas'});state.links=state.links.filter(l=>l.source!==x.id&&l.target!==x.id);state.areas.splice(i,1);save();renderEditor();renderAll()}}
  if(a==='edit-area'){openAreaEditor(Number(b.dataset.index))}
  if(a==='back-structure'){state.settings.editorTab='structure';renderEditor()}
  if(a==='save-area-detail'){const i=Number(b.dataset.index),x=state.areas[i];if(x){x.name=document.getElementById('eaName').value.trim()||x.name;x.code=makeNodeCode(x.name);x.space=document.getElementById('eaSpace').value;x.level=Number(document.getElementById('eaLevel').value);x.parentId=document.getElementById('eaParent').value;x.description=document.getElementById('eaDescription').value.trim();organiseSphericalLayout(state,state.settings.activeProfile||'me');log(`Area edited: ${x.name}.`);save();openAreaEditor(i);renderAll();toast('Area saved')}}
  if(a==='add-project'){state.projects.unshift({id:uid('p'),profile:state.settings.activeProfile||'me',space:'personal',areaId:profileAreas()[0]?.id||'',topicId:'',code:`P-${String(state.projects.length+1).padStart(2,'0')}`,title:'New Project',status:'ACTIVE',objective:'',next:'',tags:[],createdAt:now(),milestones:[],tasks:[]});save();renderEditor();renderAll()}
  if(a==='remove-project'){state.projects.splice(Number(b.dataset.index),1);save();renderEditor();renderAll()}
  if(a==='edit-project'){openProjectEditor(Number(b.dataset.index))}
  if(a==='back-projects'){state.settings.editorTab='projects';renderEditor()}
  if(a==='add-note'){openCapture('note');closeOverlay('editorOverlay')}
  if(a==='remove-note'){state.notes.splice(Number(b.dataset.index),1);save();renderEditor();renderAll()}
  if(a==='edit-note'){openNoteEditor(Number(b.dataset.index))}
  if(a==='back-notes'){state.settings.editorTab='notes';renderEditor()}
  if(a==='save-note-detail'){const i=Number(b.dataset.index),n=state.notes[i];if(n){n.title=document.getElementById('enTitle').value.trim()||n.title;n.type=document.getElementById('enType').value.trim()||'note';n.areaId=document.getElementById('enArea').value;n.topicId=document.getElementById('enTopic').value;n.body=document.getElementById('enBody').value;n.tags=document.getElementById('enTags').value.split(',').map(s=>s.trim()).filter(Boolean);n.showOnMap=document.getElementById('enMap').value==='true';const ar=areaById(n.topicId)||areaById(n.areaId);if(ar)n.space=ar.space;log(`Note edited: ${n.title}.`);save();openNoteEditor(i);renderAll();toast('Note saved')}}
  if(a==='add-link'){const aa=profileAreas();if(aa.length>1)state.links.push({id:uid('link'),profile:state.settings.activeProfile||'me',source:aa[0].id,target:aa[1].id,type:'cross'});save();renderEditor();renderAll()}
  if(a==='remove-link'){state.links.splice(Number(b.dataset.index),1);save();renderEditor();renderAll()}
  if(a==='enable-lock'){closeOverlay('editorOverlay');showSetupScreen();return}
  if(a==='save-security'){authConfig.idleMinutes=Number(document.getElementById('secIdle')?.value||15);authConfig.updatedAt=Date.now();await authSet(authConfig);resetIdleTimer();securityMsg('Auto-lock setting saved.');toast('Security setting saved')}
  if(a==='change-password'){if(!(await verifyCurrentSecurityPassword())){securityMsg('Current PIN is incorrect.');return}const np=(document.getElementById('secNew').value||'').replace(/\D/g,'').slice(0,4),nc=(document.getElementById('secConfirm').value||'').replace(/\D/g,'').slice(0,4);if(!/^\d{4}$/.test(np)){securityMsg('New PIN must be four digits.');return}if(np!==nc){securityMsg('PINs do not match.');return}authConfig.pin=await makeVerifier(np,180000);authConfig.mode='pin';delete authConfig.password;authConfig.updatedAt=Date.now();await authSet(authConfig);recoveryAuthenticated=false;securityMsg('PIN changed.');toast('PIN changed')}
  if(a==='new-recovery'){if(!(await verifyCurrentSecurityPassword())){securityMsg('Current PIN is required.');return}const key=generateRecoveryKey();authConfig.recovery=await makeVerifier(key,160000);authConfig.updatedAt=Date.now();await authSet(authConfig);securityMsg(`New recovery key: ${key} — save it now; it will not be shown again.`)}
  if(a==='disable-lock'){if(!(await verifyCurrentSecurityPassword())){securityMsg('Current PIN is required.');return}if(confirm('Disable Atlas Lock on this device?')){authConfig={enabled:false,updatedAt:Date.now()};recoveryAuthenticated=false;await authSet(authConfig);sessionStorage.removeItem('atlas_session_unlocked');securityMsg('Atlas Lock disabled on this device.');toast('Atlas Lock disabled')}}
  if(a==='snapshot'){await idbBackup(state,'manual snapshot');toast('Snapshot created')}
  if(a==='restore-latest'){const backups=await idbBackups();const latest=backups[0];if(!latest){toast('No snapshots yet');return}if(confirm(`Restore snapshot from ${fmtDate(latest.createdAt)} ${fmtTime(latest.createdAt)}? Current data will be snapshotted first.`)){await idbBackup(state,'before snapshot restore');state=ensureState(clone(latest.data));log(`Snapshot restored from ${fmtDate(latest.createdAt)}.`);await save();renderEditor();renderAll();toast('Snapshot restored')}}
  if(a==='export')exportData();
  if(a==='reset'){if(confirm('Reset Atlas to the demo structure? This replaces the data currently stored in this browser.')){await idbBackup(state,'before demo reset');state=ensureState(clone(demo));await save();renderEditor();renderAll();toast('Atlas reset')}}
  if(['add-milestone','remove-milestone','add-task','remove-task','save-project-detail'].includes(a)){const i=Number(b.dataset.index),p=state.projects[i];if(!p)return;if(a==='add-milestone'){p.milestones.push({id:uid('m'),title:'New milestone',done:false})}if(a==='remove-milestone'){p.milestones.splice(Number(b.dataset.subindex),1)}if(a==='add-task'){p.tasks.push({id:uid('t'),title:'New task',done:false})}if(a==='remove-task'){p.tasks.splice(Number(b.dataset.subindex),1)}if(a==='save-project-detail'){p.title=document.getElementById('epTitle').value.trim()||p.title;p.status=document.getElementById('epStatus').value;p.objective=document.getElementById('epObjective').value.trim();p.next=document.getElementById('epNext').value.trim();p.tags=document.getElementById('epTags').value.split(',').map(s=>s.trim()).filter(Boolean);document.querySelectorAll('[data-ep-milestone]').forEach(x=>{if(p.milestones[Number(x.dataset.epMilestone)])p.milestones[Number(x.dataset.epMilestone)].done=x.checked});document.querySelectorAll('[data-ep-milestone-title]').forEach(x=>{if(p.milestones[Number(x.dataset.epMilestoneTitle)])p.milestones[Number(x.dataset.epMilestoneTitle)].title=x.value});document.querySelectorAll('[data-ep-task]').forEach(x=>{if(p.tasks[Number(x.dataset.epTask)])p.tasks[Number(x.dataset.epTask)].done=x.checked});document.querySelectorAll('[data-ep-task-title]').forEach(x=>{if(p.tasks[Number(x.dataset.epTaskTitle)])p.tasks[Number(x.dataset.epTaskTitle)].title=x.value});log(`Project edited: ${p.title}.`);toast('Project saved')}save();openProjectEditor(i);renderAll()}
}


/* Atlas 0.11.1 · Widget workspace + branch list + dual clocks */
