const fs=require('fs');
const assert=require('assert');

const read=p=>fs.readFileSync(p,'utf8');
const boot=read('js/bootstrap.js');
const sw=read('sw.js');
const calendar=read('js/calendar.js');
const calendarCss=read('styles/calendar-extras.css');
const house=read('js/house.js');
const css=read('styles/house.css');
const entry=read('house/index.html');
const legacy=read('house/legacy.html');
const legacyJs=read('house/legacy.js');
const legacyCss=read('house/legacy.css');
const legacyCalendarJs=read('house/legacy-calendar.js');
const legacyCalendarCss=read('house/legacy-calendar.css');
const legacyUpcomingEditJs=read('house/legacy-upcoming-edit.js');
const legacyLinkColours=read('house/legacy-calendar-link-colours.js');
const legacyLinkUi=read('house/legacy-calendar-link-ui.js');
const legacyPerson=read('house/legacy-calendar-person.js');
const legacyPersonCss=read('house/legacy-calendar-person.css');
const houseVisuals=read('js/house-calendar-visuals.js');
const clarity=read('js/calendar-clarity.js');
const clarityCss=read('styles/calendar-clarity.css');
const context=read('js/widget-context.js');
const list=read('js/list-widget.js');
const server=read('js/home-server-widget.js');
const weather=read('js/weather-widget.js');
const weatherSource=read('js/header-weather.js');

assert.match(boot,/const BUILD='0169r65'/,'r65 build marker missing');
assert.match(sw,/atlas-shell-0\.16\.9-r65/,'r65 service-worker cache missing');
for(const asset of ['./js/widget-context.js','./js/house-calendar-visuals.js','./js/list-widget.js','./js/home-server-widget.js','./js/weather-widget.js','./js/house.js','./styles/weather-widget.css','./styles/house.css']){
  assert.ok(boot.includes(asset)||asset.startsWith('./styles/'),`${asset} is not booted`);
  assert.ok(sw.includes(asset),`${asset} is not offline-cached`);
}
for(const asset of ['./house/','./house/index.html','./house/legacy.html','./house/legacy.css','./house/legacy.js','./house/legacy-calendar.css','./house/legacy-calendar.js','./house/legacy-upcoming-edit.js','./house/legacy-calendar-link-colours.js','./house/legacy-calendar-link-ui.js','./house/legacy-calendar-person.js','./house/legacy-calendar-person.css'])assert.ok(sw.includes(asset),`${asset} route shell is not offline-cached`);

assert.match(entry,/new Function\('var item=\{value:1\}; return item\?\.value \?\? 0;'\)/,'/house/ must capability-test modern Atlas syntax before routing');
assert.match(entry,/legacy\?'\.\/legacy\.html\?compat=r65':'\.\.\/\?view=house'/,'modern devices must continue into the shared Atlas House route');
assert.match(entry,/Compatibility view/,'House routing shell must expose a manual legacy fallback link');
assert.match(legacy,/\.\/legacy\.css\?v=r65/,'legacy House CSS missing');
assert.match(legacy,/\.\/legacy\.js\?v=r65/,'legacy House runtime missing');
assert.match(legacy,/\.\/legacy-calendar\.css\?v=r65/,'legacy House calendar CSS missing');
assert.match(legacy,/\.\/legacy-calendar\.js\?v=r65/,'legacy House calendar writer missing');
assert.match(legacy,/\.\/legacy-upcoming-edit\.js\?v=r65/,'legacy House upcoming editor missing');
assert.match(legacy,/\.\/legacy-calendar-link-colours\.js\?v=r65/,'legacy House calendar colour/link writer missing');
assert.match(legacy,/\.\/legacy-calendar-link-ui\.js\?v=r65/,'legacy House calendar profile-link UI missing');
assert.match(legacy,/\.\/legacy-calendar-person\.js\?v=r65/,'legacy House calendar Who runtime missing');
assert.match(legacy,/\.\/legacy-calendar-person\.css\?v=r65/,'legacy House calendar Who styling missing');
assert.match(legacy,/id="houseAddTravel"/,'legacy House must expose + Travel');
assert.match(legacy,/id="houseAddEvent"/,'legacy House must expose + Event');
assert.match(legacy,/id="houseCalendarOverlay"/,'legacy House calendar entry overlay missing');
assert.doesNotMatch(legacyJs,/\?\.|\?\?|=>|\basync\b|\bawait\b|`/,'legacy House JavaScript must stay parseable by iOS 12 Safari');
assert.doesNotMatch(legacyCalendarJs,/\?\.|\?\?|=>|\basync\b|\bawait\b|`/,'legacy House calendar writer must stay parseable by iOS 12 Safari');
assert.doesNotMatch(legacyUpcomingEditJs,/\?\.|\?\?|=>|\basync\b|\bawait\b|`/,'legacy House upcoming editor must stay parseable by iOS 12 Safari');
assert.doesNotMatch(legacyLinkColours,/\?\.|\?\?|=>|\basync\b|\bawait\b|`/,'legacy House calendar colour/link runtime must stay parseable by iOS 12 Safari');
assert.doesNotMatch(legacyLinkUi,/\?\.|\?\?|=>|\basync\b|\bawait\b|`/,'legacy House calendar profile-link UI must stay parseable by iOS 12 Safari');
assert.doesNotMatch(legacyPerson,/\?\.|\?\?|=>|\basync\b|\bawait\b|`/,'legacy House calendar Who runtime must stay parseable by iOS 12 Safari');
assert.doesNotMatch(legacyCss,/color-mix\(|100dvh|100svh|100lvh/,'legacy House CSS must avoid modern-only presentation features');
assert.doesNotMatch(legacyCalendarCss,/color-mix\(|100dvh|100svh|100lvh/,'legacy House calendar CSS must avoid modern-only presentation features');
assert.doesNotMatch(legacyPersonCss,/color-mix\(|100dvh|100svh|100lvh/,'legacy House Who CSS must avoid modern-only presentation features');
assert.match(legacyJs,/ENTITY_TYPE='entity_state_v2'/,'legacy House must use Shared Atlas record-level sync records');
assert.match(legacyJs,/PROFILE='us'/,'legacy House must stay scoped to the shared Us profile');
assert.match(legacyJs,/kind==='calendar'/,'legacy House calendar must read real Atlas calendar records');
assert.match(legacyJs,/kind==='quickTodos'/,'legacy House To-do must read real Atlas quickTodos records');
assert.match(legacyJs,/data\.type==='list'/,'legacy House lists must use real Atlas List note records');
assert.match(legacyJs,/insertRecord\(value,'quickTodos'/,'legacy House must write normal Atlas To-do records');
assert.match(legacyJs,/insertRecord\(value,'notes'/,'legacy House must write normal Atlas List records');
assert.doesNotMatch(legacyJs,/indexedDB|deleteDatabase|canonical_state_v1/,'legacy House must not introduce a second Atlas database or stale canonical-state client');
assert.match(legacyCalendarJs,/PROFILE='us'/,'House-created calendar items must belong to Us');
assert.match(legacyCalendarJs,/kind:'calendar'/,'House calendar writer must create normal calendar entity records');
assert.match(legacyCalendarJs,/record_type:ENTITY_TYPE/,'House calendar writer must use current record-level sync');
assert.match(legacyCalendarJs,/profile:PROFILE/,'House calendar data must stay scoped to Us');
assert.match(legacyCalendarJs,/data-house-date/,'House calendar dates must be interactive');
assert.match(legacyCalendarJs,/openForm\('event',day\.getAttribute\('data-house-date'\)\)/,'tapping a House date must open event creation for that date');
assert.match(legacyCalendarJs,/entryType:type/,'House calendar writer must preserve event versus travel type');
assert.match(legacyCalendarJs,/flightNumber:type==='travel'/,'House travel creation must preserve flight details');
assert.match(legacyUpcomingEditJs,/data-house-calendar-id/,'legacy House upcoming rows must be editable targets');
assert.match(legacyUpcomingEditJs,/updateCalendarRecord/,'legacy House upcoming editor must update normal calendar records');
assert.match(legacyUpcomingEditJs,/sourceEventId/,'editing an entangled House event must follow its source event');
assert.match(legacyUpcomingEditJs,/mirrorShared/,'linked House copy must be updated with its source');
assert.match(legacyLinkColours,/amber:'#ae8954'/,'legacy House must use the canonical amber event colour');
assert.match(legacyLinkColours,/mini-event-dots/,'legacy House calendar dates must show per-event colour markers');
assert.match(legacyLinkColours,/marker\.style\.backgroundColor=colour\(event\.color\)/,'legacy House Upcoming must show each event colour');
assert.match(legacyLinkColours,/source\.entangledId=sharedId/,'House-created linked event must point from personal source to Us copy');
assert.match(legacyLinkColours,/shared\.sourceEventId=sourceId/,'House-created linked Us copy must point back to its personal source');
assert.match(legacyLinkColours,/profile='us'|shared\.profile='us'/,'House-created shared copy must stay in Us');
assert.match(legacyLinkColours,/recordRow\(target,source\),recordRow\(target,shared\)/,'House profile linking must create the source and shared records together');
assert.match(legacyLinkUi,/id="houseCalendarLinkProfile"/,'House calendar creation must expose profile linking');
assert.match(legacyLinkUi,/Fraser \+ Us \/ House/,'House calendar must offer Fraser as a linked destination');
assert.match(legacyLinkUi,/Alyssa \+ Us \/ House/,'House calendar must offer Alyssa as a linked destination');
assert.match(legacyPerson,/fraser:'Fraser',alyssa:'Alyssa',together:'Together'/,'House event Who choices missing');
assert.match(legacyPerson,/data\.person=LABELS\[person\]\?person:'together'/,'House event Who must persist to the record');
assert.match(legacyPerson,/data\.person=source\.person/,'House linked Us copy must carry Who');
assert.match(legacyPerson,/house-event-person/,'House Upcoming must render person first');
assert.match(legacyPerson,/houseCalendarTypeSelect/,'House event editor must expose Entry type');
assert.match(legacyPerson,/houseCalendarMetaRow/,'House event editor must pair Time zone and Colour');
assert.match(legacyPerson,/houseCalendarAreaField/,'House event editor must keep Area after Time zone and Colour');
assert.match(legacyPerson,/notes\.insertAdjacentElement\('afterend',link\)/,'House Link to profiles must sit after Notes');
assert.match(calendar,/CALENDAR_PEOPLE=Object\.freeze\(\{fraser:'Fraser',alyssa:'Alyssa',together:'Together'\}\)/,'normal Atlas event Who choices missing');
assert.match(calendar,/id=\"calPerson\"/,'normal Atlas event editor must expose Who');
assert.match(calendar,/Event \/ appointment/,'ordinary event field must be labelled Event / appointment');
assert.match(calendar,/person:entryType==='travel'\?'':CALENDAR_PEOPLE\[person\]/,'normal Atlas must persist Who on ordinary events');
assert.match(calendar,/person:source\.entryType==='travel'\?'':source\.person/,'normal Atlas must propagate Who to linked Us copies');
assert.match(calendar,/cal-person-event/,'normal Atlas calendar must render person-first event cards');
assert.match(calendarCss,/\.cal-person-copy/,'normal Atlas person-first event styling missing');
assert.match(context,/calendarEventPersonLabel\(e\)/,'shared Upcoming widget must render Who first');
assert.match(houseVisuals,/eventHue\(event\)/,'modern House calendar must reuse canonical event colours');
assert.match(houseVisuals,/house-mini-event-dots/,'modern House calendar must show colour markers');
assert.match(clarity,/Link to profiles/,'personal calendar must visibly label profile linking');
assert.match(clarity,/Us \/ House/,'profile linking must expose the Us / House destination');
assert.match(clarity,/function orderCalendarForm\(\)/,'normal Atlas calendar form ordering helper missing');
assert.match(clarity,/form\.insertBefore\(entryType,title\)/,'normal Atlas Entry type must precede Who and details');
assert.match(clarity,/title\.insertAdjacentElement\('beforebegin',person\)/,'normal Atlas Who must precede event details');
assert.match(clarity,/timeRow\.insertAdjacentElement\('afterend',meta\)/,'normal Atlas Time zone and Colour must follow Date/Start/End');
assert.match(clarity,/meta\.insertAdjacentElement\('afterend',area\)/,'normal Atlas Area must follow Time zone and Colour');
assert.match(clarity,/area\.insertAdjacentElement\('afterend',notes\)/,'normal Atlas Notes must follow Area');
assert.match(clarity,/notes\.insertAdjacentElement\('afterend',link\)/,'normal Atlas Link to profiles must follow Notes');
assert.match(clarity,/link\.insertAdjacentElement\('afterend',actions\)/,'normal Atlas Save event must follow Link to profiles');
assert.match(clarity,/openUpcomingForEdit/,'normal Atlas upcoming rows must open calendar editing');
assert.match(clarity,/row\.style\.display='flex'/,'personal profile linking must be forced visible');
assert.match(clarityCss,/\.entangle-row/,'profile linking must have a visible calendar treatment');

assert.match(house,/\{id:'house',name:'House'\}/,'House navigation item missing');
assert.match(house,/renderWidget\(id,\{profileId:HOUSE_PROFILE\}\)/,'House must compose the real Atlas widget renderer');
assert.match(house,/HOUSE_PROFILE='us'/,'House must use the shared Us context');
for(const id of ['calendar','upcoming','weather','list','todo','server'])assert.ok(house.includes(`slot('${id}','${id}')`),`House ${id} widget slot missing`);
assert.doesNotMatch(house,/HOUSE_MOCK|houseSnapshot|eventRows|checklistRows|house-panel|house-clock/,'House must not invent parallel widgets or mock household data');
assert.doesNotMatch(css,/--bg:|--paper:|--ink:|background:radial-gradient|\.topbar[^\n]*display:none/,'House must not introduce a separate theme or hide Atlas chrome');
assert.match(css,/grid-template-areas:"calendar calendar upcoming" "weather list todo" "server server server"/,'House 4:3 widget composition missing');
assert.match(css,/\.house-atlas-board \.widget-body\{overflow:hidden!important;max-height:none!important\}/,'House widgets must not use internal scrollbars');
assert.match(css,/body\.atlas-house-view\{overflow:hidden\}/,'Landscape House surface must not page-scroll');
assert.match(css,/height:calc\(100dvh - 120px\)/,'House board must size to the visible landscape viewport');
assert.match(css,/\.house-calendar\{min-height:292px\}/,'House Calendar must reserve full-month height');
assert.match(context,/todoWidget=function\(options=/,'profile-aware real To-do widget missing');
assert.match(context,/upcomingWidget=function\(options=/,'profile-aware real Upcoming widget missing');
assert.match(context,/calendarWidget=function\(options=/,'profile-aware real Calendar widget missing');
assert.match(list,/ATLAS_WIDGETS\.list=/,'List must be a first-class Atlas widget');
assert.match(list,/note\.type==='list'/,'List must use synced Atlas notes rather than a parallel store');
assert.match(list,/note=>note\.type!=='list'/,'List records must stay out of ordinary note surfaces');
assert.match(server,/ATLAS_WIDGETS\.server=/,'Home Server must be a first-class Atlas widget');
assert.match(weather,/ATLAS_WIDGETS\.weather=/,'Weather must be a first-class Atlas widget');
assert.match(weatherSource,/getCurrent:currentSnapshot/,'Weather widget must reuse the header weather cache/source');
assert.match(weatherSource,/iconFor/,'Weather source must expose condition iconography');
assert.doesNotMatch(weather,/fetch\s*\(|localStorage|indexedDB/,'Weather widget must reuse the shared weather source rather than create another feed');
assert.match(sw,/shellNavigation/,'service worker must distinguish root shell navigation');
assert.match(sw,/response&&response\.ok&&shellNavigation/,'/house/ navigation must not overwrite cached Atlas root shell');

console.log('atlas house shared widgets + r65 calendar form layout contract ok');
