const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {webcrypto}=require('node:crypto');
const source=fs.readFileSync('js/cloud.js','utf8');let userId='owner',profileId='profile-me',row=null,calls=[];
function query(table){const q={table,filters:[],select(columns){this.columns=columns;calls.push(['select',table,columns]);return this},eq(k,v){this.filters.push([k,v]);return this},order(k,o){this.orderValue=[k,o];return this},limit(n){this.limitValue=n;return this},async single(){return{data:{id:'vault-1',name:'Atlas',created_by:userId},error:null}},async maybeSingle(){calls.push(['result',table,[...this.filters],this.orderValue,this.limitValue]);if(table==='atlas_profiles')return{data:{id:profileId,vault_id:'vault-1',profile_key:'me',kind:'person',owner_user_id:userId},error:null};return{data:row,error:null}},insert(){throw Error('restore must not insert')},update(){throw Error('restore must not update')},upsert(){throw Error('restore must not upsert')},delete(){throw Error('restore must not delete')}};return q}
const auth={getSession:async()=>({data:{session:{user:{id:userId}}},error:null}),getUser:async()=>({data:{user:{id:userId,email:'me@test'}},error:null}),onAuthStateChange:()=>({}),signOut:async()=>({error:null})};
const listeners={};const context={navigator:{onLine:true},crypto:webcrypto,TextEncoder,Uint8Array,CustomEvent:function(){},Date,window:{ATLAS_CLOUD_CONFIG:{url:'x',publishableKey:'public'},supabase:{createClient:()=>({auth,from:query})},addEventListener:(n,f)=>listeners[n]=f,dispatchEvent:()=>{}}};context.window.window=context.window;vm.createContext(context);vm.runInContext(source,context);

const canonical=value=>Array.isArray(value)?`[${value.map(canonical).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`:JSON.stringify(value);
async function expectedId(value){const digest=await webcrypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(value)));return'sha256-'+Buffer.from(digest).toString('hex')}
const payload={schema:'atlas_me_backup_snapshot',version:1,profileKey:'me',dataVersion:8,areas:[{id:'a',profile:'me'}],links:[],projects:[],notes:[],daily:[],calendar:[],quickTodos:[],scratch:''};
(async()=>{const cloud=context.window.AtlasCloud;await cloud.init();assert.equal((await cloud.latestMeBackupSnapshot()).ok,false);assert.equal(calls.filter(x=>x[1]==='atlas_records').length,0);await cloud.testAccess();context.navigator.onLine=false;assert.equal((await cloud.latestMeBackupSnapshot()).ok,false);context.navigator.onLine=true;await cloud.testAccess();assert.equal((await cloud.getMeBackupSnapshot('bad')).ok,false);assert.equal(calls.filter(x=>x[1]==='atlas_records').length,0);
 await cloud.testAccess();const id=await expectedId(payload);row={profile_id:profileId,record_type:'backup_snapshot_v1',record_id:id,payload,created_at:'2026-01-01T00:00:00Z',revision:1};let result=await cloud.latestMeBackupSnapshot();assert.equal(result.ok,true);let read=calls.filter(x=>x[1]==='atlas_records').at(-1);assert.deepEqual(read[2],[['profile_id',profileId],['record_type','backup_snapshot_v1']]);assert.equal(JSON.stringify(read[3]),JSON.stringify(['created_at',{ascending:false}]));assert.equal(read[4],1);
 profileId='profile-new';row={...row,profile_id:profileId};await cloud.testAccess();result=await cloud.getMeBackupSnapshot(id);assert.equal(result.ok,true);read=calls.filter(x=>x[1]==='atlas_records').at(-1);assert.ok(read[2].some(x=>x[0]==='profile_id'&&x[1]==='profile-new'));assert.ok(read[2].some(x=>x[0]==='record_id'&&x[1]===id));
 for(const bad of [{...payload,schema:'wrong'},{...payload,profileKey:'us'},{...payload,dataVersion:9},{...payload,notes:[{profile:'alyssa'}]},{...payload,notes:[{profile:'me',auth:{token:'x'}}]},{...payload,notes:[{profile:'me',n:Infinity}]}]){await cloud.testAccess();row={...row,payload:bad};assert.equal((await cloud.latestMeBackupSnapshot()).ok,false)}
 const brokenGraphs=[
  {...payload,areas:[{id:'a',profile:'me',parentId:'missing'}]},
  {...payload,links:[{id:'l',profile:'me',source:'a',target:'alyssa-area'}]},
  {...payload,projects:[{id:'p',profile:'me',areaId:'missing',milestones:[],tasks:[]}]},
  {...payload,notes:[{id:'n',profile:'me',topicId:'missing'}]},
  {...payload,daily:[{id:'d',profile:'me',areaId:'missing'}]},
  {...payload,calendar:[{id:'c',profile:'me',areaId:'missing'}]},
  {...payload,areas:[{id:'a',profile:'me'},{id:'a',profile:'me'}]}
 ];
 for(const bad of brokenGraphs){await cloud.testAccess();row={...row,payload:bad,record_id:await expectedId(bad)};assert.equal((await cloud.latestMeBackupSnapshot()).ok,false)}
 await cloud.testAccess();row={...row,payload,record_id:'sha256-'+'a'.repeat(64)};assert.equal((await cloud.latestMeBackupSnapshot()).ok,false);await cloud.testAccess();row={...row,payload,record_id:id};assert.equal((await cloud.latestMeBackupSnapshot()).ok,true);assert.ok(!calls.some(x=>['insert','update','upsert','delete'].includes(x[0])));console.log('Cloud restore transport contracts: PASS')})().catch(e=>{console.error(e);process.exitCode=1});
