const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('js/widgets.js','utf8');
const block=source.split('let cloudAccessResult=null,cloudBackupResult=null;',2)[1].split('function calendarWidget()',1)[0];
const listener=source.match(/window\.addEventListener\('atlascloudstatus',[^\n]+/)[0];
let restoreInvalidations=0;let cloudStatus={state:'CONNECTED',message:'Cloud access verified',email:'me@example.test',authenticated:true,verified:true},statusListener;
const context={state:{settings:{activeProfile:'me',activeTab:'other'}},window:{AtlasCloud:{getStatus:()=>cloudStatus},AtlasCloudRestore:{invalidate:()=>restoreInvalidations++},addEventListener:(name,fn)=>{if(name==='atlascloudstatus')statusListener=fn}},esc:value=>String(value),widgetShell:(_id,body)=>body,widgetIsOpen:()=>false,renderHome:()=>{}};
vm.createContext(context);vm.runInContext(`let cloudAccessResult=null,cloudBackupResult=null;${block}${listener}`,context);
vm.runInContext("cloudAccessResult={ok:true,vaultName:'Atlas',profile:{name:'Me'}}",context);
let connected=vm.runInContext('syncWidget()',context);assert.match(connected,/CLOUD CONNECTED/);assert.match(connected,/ME CLOUD RESTORE/);assert.match(connected,/Preview restore/);
cloudStatus={state:'SIGNED OUT',message:'Sign in',authenticated:false,verified:false};statusListener({detail:cloudStatus});
assert.doesNotMatch(vm.runInContext('syncWidget()',context),/CLOUD CONNECTED/,'auth loss clears successful access display');
cloudStatus={state:'CONNECTED',message:'Cloud access verified',authenticated:true,verified:true};vm.runInContext("cloudAccessResult={ok:true,vaultName:'Atlas',profile:{name:'Me'}};state.settings.activeProfile='us'",context);
const localOnly=vm.runInContext('syncWidget()',context);assert.match(localOnly,/LOCAL ONLY/);assert.doesNotMatch(localOnly,/Preview restore|Restore Me/);assert.ok(restoreInvalidations>0);vm.runInContext("state.settings.activeProfile='me'",context);
assert.doesNotMatch(vm.runInContext('syncWidget()',context),/CLOUD CONNECTED/,'leaving Me clears successful access display');assert.match(source,/AtlasCloudRestore\?\.invalidate/);
console.log('Cloud widget invalidation contracts: PASS');
