const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {webcrypto}=require('node:crypto');
const source=fs.readFileSync('js/cloud.js','utf8');let inserted=[],calls=[],existing=false,userId='owner';
function query(table){const q={table,filters:[],select(){calls.push(['select',table]);return this},eq(k,v){this.filters.push([k,v]);return this},async single(){return{data:{id:'vault-1',name:'Atlas',created_by:userId},error:null}},async maybeSingle(){if(table==='atlas_profiles')return{data:{id:'profile-me',vault_id:'vault-1',profile_key:'me',name:'Me',kind:'person',owner_user_id:userId},error:null};return{data:existing?{record_id:'same'}:null,error:null}},async insert(row){calls.push(['insert',table]);inserted.push({table,row});return{error:null}}};return q}
const auth={getSession:async()=>({data:{session:{user:{id:userId,email:'me@test'}}},error:null}),getUser:async()=>({data:{user:{id:userId,email:'me@test'}},error:null}),onAuthStateChange:()=>({}),signOut:async()=>({error:null})};
const context={navigator:{onLine:true},crypto:webcrypto,TextEncoder,Uint8Array,CustomEvent:function(){},Date,window:{ATLAS_CLOUD_CONFIG:{url:'x',publishableKey:'sb_publishable_test'},supabase:{createClient:()=>({auth,from:query})},addEventListener:()=>{},dispatchEvent:()=>{}}};context.window.window=context.window;vm.createContext(context);vm.runInContext(source,context);
const payload={schema:'atlas_me_backup_snapshot',version:1,profileKey:'me',dataVersion:8,areas:[{id:'area',profile:'me'}],links:[],projects:[],notes:[{id:'note',profile:'me',title:'Safe'}],daily:[],calendar:[],quickTodos:[],scratch:''};
const canonical=value=>Array.isArray(value)?`[${value.map(canonical).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`:JSON.stringify(value);
async function expectedId(value){const digest=await webcrypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(value)));return'sha256-'+Buffer.from(digest).toString('hex')}
(async()=>{const cloud=context.window.AtlasCloud;await cloud.init();const id=await expectedId(payload),valid={recordType:'backup_snapshot_v1',recordId:id,payload,clientUpdatedAt:1700000000000};
 assert.equal((await cloud.appendMeBackupSnapshot(valid)).ok,false);assert.equal(inserted.length,0,'unverified cannot write');
 await cloud.testAccess();assert.equal((await cloud.meBackupExists('not-a-fingerprint')).ok,false);assert.equal(calls.filter(([,table])=>table==='atlas_records').length,0,'invalid existence ID cannot query records');
 for(const badTime of [NaN,Infinity,-1,0,1.5]){await cloud.testAccess();assert.equal((await cloud.appendMeBackupSnapshot({...valid,clientUpdatedAt:badTime})).ok,false);assert.equal(inserted.length,0)}
 await cloud.testAccess();assert.equal((await cloud.appendMeBackupSnapshot({...valid,recordId:'sha256-'+'a'.repeat(64)})).ok,false);assert.equal(inserted.length,0,'caller fingerprint mismatch cannot insert');
 for(const badPayload of [{...payload,schema:'wrong'},{...payload,profileKey:'us'},{...payload,dataVersion:0},{...payload,unexpected:[]},{...payload,notes:[{profile:'alyssa'}]},{...payload,calendar:[{profile:'us'}]},{...payload,notes:[{profile:'me',access_token:'secret'}]},{...payload,calendar:[{profile:'me',entangledId:'us-event'}]}]){await cloud.testAccess();assert.equal((await cloud.appendMeBackupSnapshot({...valid,recordId:undefined,payload:badPayload})).ok,false);assert.equal(inserted.length,0)}
 await cloud.testAccess();const result=await cloud.appendMeBackupSnapshot({...valid,recordId:undefined});assert.equal(result.ok,true);assert.equal(result.recordId,id);assert.equal(inserted.length,1);assert.equal(inserted[0].table,'atlas_records');assert.deepEqual(JSON.parse(JSON.stringify(inserted[0].row)),{profile_id:'profile-me',record_type:'backup_snapshot_v1',record_id:id,payload,client_updated_at:1700000000000});assert.equal(typeof inserted[0].row.client_updated_at,'number');assert.equal(calls.filter(x=>x[0]==='insert').length,1);assert.ok(!calls.some(x=>['update','upsert','delete'].includes(x[0])));
 existing=true;const again=await cloud.appendMeBackupSnapshot(valid);assert.equal(again.alreadyBackedUp,true);assert.equal(again.recordId,id);assert.equal(inserted.length,1);context.navigator.onLine=false;assert.equal((await cloud.appendMeBackupSnapshot(valid)).ok,false);assert.equal(inserted.length,1);console.log('Cloud backup transport contracts: PASS');
})().catch(e=>{console.error(e);process.exitCode=1});
