const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync('js/relay-transport.js','utf8');const tick=()=>new Promise(resolve=>setImmediate(resolve));
function harness(initialToken=null){
 const listeners={},docListeners={},events=[],timers=[];let stored=initialToken,online=true,hidden=false,rows=[],ackFailures=0,fetchHeld=null,ingestHeld=null,saveHeld=null;const calls=[];
 const state={settings:{activeProfile:'me'},relayLedger:{},relayReceipts:[],notes:[],areas:[],activity:[]};
 const AtlasRelay={validate:p=>p?.valid===false?{ok:false,errors:['target ambiguous']}:{ok:true},ingest:async p=>{const old=state.relayLedger[p.relayId];if(old){if(old.fingerprint!==p.fingerprint)return{ok:false,errors:['Relay ID conflict']};return{ok:true,duplicate:true,recordId:old.recordId}}const id='local-'+p.relayId;state.relayLedger[p.relayId]={fingerprint:p.fingerprint,recordId:id};if(p.operation==='create_note')state.notes.push({id,body:p.content.body||''});if(p.operation==='append_note'){const n=state.notes.find(x=>x.id===p.target.noteId);n.body+=(n.body?'\n\n':'')+p.content.body}if(p.operation==='create_area')state.areas.push({id,name:p.content.name});if(ingestHeld)await ingestHeld;return{ok:true,duplicate:false,recordId:id}}};
 const context={state,navigator:{get onLine(){return online}},document:{get hidden(){return hidden},addEventListener:(n,f)=>docListeners[n]=f},CustomEvent:function(n,o){return{type:n,detail:o.detail}},setTimeout:(f,ms)=>{timers.push({f,ms});return timers.length},clearTimeout:()=>{},authStoreGet:async()=>stored,authStoreSet:async(k,v)=>{stored=v},authStoreRemove:async()=>{stored=null},save:async()=>{if(saveHeld)await saveHeld},fetch:async(url,options)=>{calls.push({url,options});if(url.endsWith('/fetch_atlas_relay')){if(fetchHeld)await fetchHeld;return{ok:true,json:async()=>rows}}if(ackFailures-->0)return{ok:false,status:503};return{ok:true}},window:{addEventListener:(n,f)=>listeners[n]=f,dispatchEvent:e=>events.push(e),AtlasRelay}};context.window.window=context.window;vm.createContext(context);vm.runInContext(source,context);
 return{context,state,calls,timers,listeners,docListeners,events,transport:context.window.AtlasRelayTransport,setRows:v=>rows=v,setOnline:v=>online=v,setHidden:v=>hidden=v,failAcks:n=>ackFailures=n,holdFetch:p=>fetchHeld=p,holdIngest:p=>ingestHeld=p,holdSave:p=>saveHeld=p,getStored:()=>stored};
}
const env=(id,operation='create_note',extra={})=>({version:1,relayId:id,operation,profileId:'me',target:{inbox:true},content:{title:id,body:'body'},fingerprint:'fp-'+id,...extra});
(async()=>{
 const empty=harness();await empty.transport.init();assert.equal(empty.calls.length,0,'no token -> no network');empty.setOnline(false);await empty.transport.setAccessKey('relay-secret');assert.equal(empty.calls.length,0,'offline -> no network');assert.doesNotMatch(JSON.stringify(empty.state),/relay-secret/);
 const h=harness('relay-secret');h.setRows([ {relay_id:'create',payload:env('create')} ]);await h.transport.init();assert.equal(h.state.notes.length,1,'configured init immediately ingests');
 const firstFetch=h.calls[0];assert.match(firstFetch.url,/\/rest\/v1\/rpc\/fetch_atlas_relay$/);assert.equal(firstFetch.options.headers.apikey,'sb_publishable_hwyVvfkmHLdFHflWBClT5A_8axCzHHA');assert.equal('Authorization' in firstFetch.options.headers,false,'publishable key is not Bearer auth');assert.equal(firstFetch.options.headers['Content-Type'],'application/json');assert.ok(h.calls.every(c=>/\/rpc\/(fetch_atlas_relay|ack_atlas_relay)$/.test(c.url)));assert.doesNotMatch(source,/relay_inbox|Authorization|\.from\(|SELECT |INSERT |UPDATE |DELETE /i);
 await h.transport.check();assert.equal(h.state.notes.length,1,'exact create retry does not duplicate');assert.equal(JSON.parse(h.calls.at(-1).options.body).p_result.duplicate,true);
 h.setRows([{relay_id:'create',payload:env('create','create_note',{fingerprint:'changed',content:{title:'x',body:'changed'}})}]);await h.transport.check();assert.equal(h.state.notes.length,1);assert.equal(JSON.parse(h.calls.at(-1).options.body).p_status,'rejected','changed relay ID is rejected');
 h.state.notes.push({id:'append-target',body:'first'});h.setRows([{relay_id:'append',payload:env('append','append_note',{target:{noteId:'append-target'},content:{body:'second'}})}]);await h.transport.check();await h.transport.check();assert.equal(h.state.notes.find(n=>n.id==='append-target').body,'first\n\nsecond','append exact retry once');
 h.setRows([{relay_id:'area',payload:env('area','create_area',{target:{root:true},content:{name:'New Area'}})}]);await h.transport.check();await h.transport.check();assert.equal(h.state.areas.filter(a=>a.name==='New Area').length,1,'area exact retry once');
 h.setRows([{relay_id:'ack-retry',payload:env('ack-retry')}]);const contentEventsBefore=h.events.filter(e=>e.type==='atlasrelaycontent'&&e.detail.mutated).length;h.failAcks(1);await h.transport.check();assert.equal(h.state.notes.filter(n=>n.id==='local-ack-retry').length,1,'local ingest survives failed ack');assert.equal(h.events.filter(e=>e.type==='atlasrelaycontent'&&e.detail.mutated).length,contentEventsBefore+1,'failed ack still emits one content event');await h.transport.check();assert.equal(h.state.notes.filter(n=>n.id==='local-ack-retry').length,1,'ack retry does not mutate twice');assert.equal(h.events.filter(e=>e.type==='atlasrelaycontent'&&e.detail.mutated).length,contentEventsBefore+1,'duplicate retry emits no second content event');assert.equal(JSON.parse(h.calls.at(-1).options.body).p_result.duplicate,true,'eventual ack reports duplicate');
 const contentBefore=JSON.stringify({notes:h.state.notes,areas:h.state.areas});h.setRows([{relay_id:'bad',operation:'create_note',payload:{...env('bad'),valid:false}}]);h.failAcks(1);await h.transport.check();assert.equal(h.state.relayReceipts.filter(r=>r.relayId==='bad').length,1);await h.transport.check();assert.equal(h.state.relayReceipts.filter(r=>r.relayId==='bad').length,1,'failed rejection ack does not spam history');const wrongBefore=JSON.stringify({notes:h.state.notes,areas:h.state.areas});h.setRows([{relay_id:'wrong-profile',payload:{...env('wrong-profile'),profileId:'alyssa'}}]);await h.transport.check();assert.equal(JSON.stringify({notes:h.state.notes,areas:h.state.areas}),wrongBefore,'wrong profile does not mutate content');
 h.setRows([{relay_id:'profile-race',payload:env('profile-race')}]);let releaseIngest;const ingestGate=new Promise(r=>releaseIngest=r);h.holdIngest(ingestGate);const raceEvents=h.events.filter(e=>e.type==='atlasrelaycontent'&&e.detail.mutated).length,raceAckBefore=h.calls.filter(c=>c.url.endsWith('/ack_atlas_relay')).length;const raceCheck=h.transport.check();await tick();h.context.state.settings.activeProfile='alyssa';h.transport.profileChanged();releaseIngest();await raceCheck;assert.equal(h.state.notes.filter(n=>n.id==='local-profile-race').length,1,'local mutation survives profile switch');assert.equal(h.events.filter(e=>e.type==='atlasrelaycontent'&&e.detail.mutated).length,raceEvents+1,'mutation event emitted while ack paused');assert.equal(h.calls.filter(c=>c.url.endsWith('/ack_atlas_relay')).length,raceAckBefore,'no accepted ack outside Me');h.holdIngest(null);h.context.state.settings.activeProfile='me';h.transport.profileChanged();await tick();assert.equal(h.state.notes.filter(n=>n.id==='local-profile-race').length,1,'Me retry remains duplicate');assert.equal(h.events.filter(e=>e.type==='atlasrelaycontent'&&e.detail.mutated).length,raceEvents+1,'Me retry emits no mutation event');assert.equal(JSON.parse(h.calls.at(-1).options.body).p_status,'accepted');assert.equal(JSON.parse(h.calls.at(-1).options.body).p_result.duplicate,true);
 h.setRows([{relay_id:'reject-race',payload:{...env('reject-race'),valid:false}}]);let releaseSave;const saveGate=new Promise(r=>releaseSave=r);h.holdSave(saveGate);const rejectAckBefore=h.calls.filter(c=>c.url.endsWith('/ack_atlas_relay')).length;const rejectCheck=h.transport.check();await tick();h.context.state.settings.activeProfile='us';h.transport.profileChanged();releaseSave();await rejectCheck;assert.equal(h.state.relayReceipts.filter(r=>r.relayId==='reject-race').length,1,'one rejection persisted during switch');assert.equal(h.calls.filter(c=>c.url.endsWith('/ack_atlas_relay')).length,rejectAckBefore,'no rejected ack outside Me');h.holdSave(null);h.context.state.settings.activeProfile='me';h.transport.profileChanged();await tick();assert.equal(h.state.relayReceipts.filter(r=>r.relayId==='reject-race').length,1,'rejection retry remains deduplicated');assert.equal(JSON.parse(h.calls.at(-1).options.body).p_status,'rejected','eventual rejected ack succeeds');
 const before=h.calls.length;h.context.state.settings.activeProfile='alyssa';h.transport.profileChanged();await h.transport.check();assert.equal(h.calls.length,before,'Alyssa makes no calls');assert.equal(h.transport.getState().state,'LOCAL ONLY');h.context.state.settings.activeProfile='me';h.transport.profileChanged();await tick();assert.ok(h.calls.length>before,'return to Me resumes');
 h.setHidden(true);const hiddenCalls=h.calls.length;await h.transport.check();assert.equal(h.calls.length,hiddenCalls);h.setHidden(false);h.docListeners.visibilitychange();await tick();assert.ok(h.calls.length>hiddenCalls,'visibility return checks');assert.ok(h.timers.some(t=>t.ms===5000),'five-second polling scheduled');
 h.setOnline(false);const offlineCalls=h.calls.length;h.listeners.offline();await h.transport.check();assert.equal(h.calls.length,offlineCalls);h.setOnline(true);h.listeners.online();await tick();assert.ok(h.calls.length>offlineCalls,'online checks immediately');h.listeners.focus();await tick();
 let release;const gate=new Promise(r=>release=r);h.holdFetch(gate);const pending=h.transport.check(),overlap=await h.transport.check();assert.equal(overlap.overlap,true);const midflightNotes=h.state.notes.length,midflightCalls=h.calls.length;h.context.state.settings.activeProfile='alyssa';h.transport.profileChanged();release();await pending;assert.equal(h.state.notes.length,midflightNotes,'profile switch stops in-flight processing');assert.equal(h.calls.length,midflightCalls,'no acknowledgement after switch');h.context.state.settings.activeProfile='me';h.holdFetch(null);h.transport.profileChanged();await tick();
 await h.transport.removeAccessKey();assert.equal(h.getStored(),null);assert.equal(h.transport.getState().state,'RELAY NOT CONNECTED');assert.doesNotMatch(JSON.stringify(h.state),/relay-secret/);
 const ui=fs.readFileSync('js/ui.js','utf8');assert.doesNotMatch(ui,/AtlasRelayTransport\?\.invalidate/);assert.match(ui,/activeProfile=e\.target\.value;window\.AtlasRelayTransport\?\.profileChanged\(\)/);
 console.log('Relay transport runtime contracts: PASS');
})().catch(e=>{console.error(e);process.exitCode=1});
