const fs=require('fs');
const assert=require('assert');
const tokens=fs.readFileSync('styles/tokens.css','utf8');
const overviewCss=fs.readFileSync('styles/network-overview.css','utf8');
const overview=fs.readFileSync('js/network-overview.js','utf8');
const capture=fs.readFileSync('js/capture-flow-fix.js','utf8');
const visibility=fs.readFileSync('js/widget-visibility-hotfix.js','utf8');
const localDrag=fs.readFileSync('js/window-drag-local.js','utf8');
const theme=fs.readFileSync('styles/theme-system.css','utf8');
const hotfix=fs.readFileSync('styles/r18-stability-hotfix.css','utf8');
const material=fs.readFileSync('styles/r21-material-balance.css','utf8');
const material22=fs.readFileSync('styles/r22-material-fields.css','utf8');
const bootstrap=fs.readFileSync('js/bootstrap.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');

assert(tokens.includes('--bg:#070b10'),'historical Atlas night palette must remain available beneath the refinement layer');
assert(tokens.includes('html:not(.atlas-ready)'),'minimal no-flash boot guard must remain');
assert(!bootstrap.includes('ops-refinement.css'),'must not load rejected Ops visual overrides');
assert(!bootstrap.includes('window-material.css'),'must not load rejected experimental material layer');
assert(!bootstrap.includes('ops-r5.css'),'must not load rejected r5 palette layer');
assert(bootstrap.includes("loadStyle('./styles/network-overview.css')"),'network overview style must load');
assert(bootstrap.includes("loadStyle('./styles/theme-system.css')"),'approved native refinement must load');
assert(bootstrap.includes("loadStyle('./styles/r18-stability-hotfix.css')"),'r18 stability hotfix must remain loaded');
assert(bootstrap.includes("loadStyle('./styles/r21-material-balance.css')"),'r21 material balance must remain');
assert(bootstrap.includes("loadStyle('./styles/r22-material-fields.css')"),'r22 material/field layer must load last');
assert(!bootstrap.includes("loadScript('./js/window-drag.js'"),'rejected global movable-window runtime must remain disabled');
assert(bootstrap.includes("loadScript('./js/window-drag-local.js','Atlas local movable windows v0.16.9-r21')"),'local window drag runtime must remain');
assert(bootstrap.includes('const SYNC_V2_ENABLED=false'),'automatic record-level sync must remain explicitly paused during recovery');
assert(bootstrap.includes("loadScript('./js/widget-visibility-hotfix.js','Atlas widget visibility hotfix v0.16.9-r20')"),'widget visibility hotfix must remain loaded');
assert(bootstrap.includes("if(SYNC_V2_ENABLED)"),'sync runtime must remain behind the emergency recovery gate');
assert(bootstrap.includes("loadScript('./js/sync-v2.js','Atlas record-level sync')"),'sync runtime path must remain available behind the gate');
assert(bootstrap.includes("paused:true"),'paused sync status must be exposed to the UI');
assert(capture.includes('[data-atlas-aligned-capture]'),'capture launcher handoff contract missing');
assert(overview.includes('AtlasNetworkOverview'),'network overview runtime contract missing');
assert(overviewCss.includes('.atlas-network-minimap'),'network overview presentation missing');
assert(theme.includes('#atlasCaptureLauncher'),'production theme must explicitly style Capture glass');
assert(hotfix.includes('box-shadow:none!important'),'decorative pane shadows must remain removed');
assert(material.includes('backdrop-filter:blur(3px)!important'),'r21 must preserve low-flare 3px frost');
assert(material22.includes('--atlas-float-glass:rgba(7,11,15,.46)'),'r22 night glass must increase material opacity');
assert(material22.includes('var(--atlas-select-bg) 74%'),'text fields must use the same fill family as dropdowns');
assert(material22.includes('.atlas-project-rich-body'),'rich project fields must share the field material');
assert(material22.includes('.atlas-note-compose'),'note text-entry surfaces must share the field material');
assert(visibility.includes('scrollIntoView'),'opened docked widgets must be revealed if outside the viewport');
assert(visibility.includes('clampFloating'),'floating widgets must be clamped into the viewport');
assert(localDrag.includes("handle.addEventListener('pointerdown'"),'local drag must bind pointerdown directly to the handle');
assert(!localDrag.includes("document.addEventListener('pointerdown'"),'local drag must not intercept document pointerdown');
assert(sw.includes("atlas-shell-0.16.9-r22"),'r22 cache version missing');
assert(sw.includes("'./styles/r22-material-fields.css'"),'r22 material/field CSS must be cached');
assert(sw.includes("'./js/widget-visibility-hotfix.js'"),'widget visibility hotfix must be cached');
assert(sw.includes("'./js/window-drag-local.js'"),'local window drag runtime must be cached');
assert(!sw.includes("'./js/window-drag.js'"),'rejected global movable-window runtime must not remain in APP_SHELL');
assert(!sw.includes("'./assets/lock-terrain.gif'"),'removed lock artwork must not remain offline-critical');

console.log('Atlas v0.16.9-r22 material + fields + recovery compatibility: PASS');
