const fs=require('fs');
const assert=require('assert');
const tokens=fs.readFileSync('styles/tokens.css','utf8');
const overviewCss=fs.readFileSync('styles/network-overview.css','utf8');
const overview=fs.readFileSync('js/network-overview.js','utf8');
const capture=fs.readFileSync('js/capture-flow-fix.js','utf8');
const visibility=fs.readFileSync('js/widget-visibility-hotfix.js','utf8');
const localDrag=fs.readFileSync('js/window-drag-local.js','utf8');
const theme=fs.readFileSync('styles/theme-system.css','utf8');
const hotfix=fs.readFileSync('styles/r18-stability-hotfix.css','utf8');
const material=fs.readFileSync('styles/r21-material-balance.css','utf8');
const bootstrap=fs.readFileSync('js/bootstrap.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');

assert(tokens.includes('--bg:#070b10'),'historical Atlas night palette must remain available beneath the refinement layer');
assert(tokens.includes('html:not(.atlas-ready)'),'minimal no-flash boot guard must remain');
assert(!bootstrap.includes('ops-refinement.css'),'must not load rejected Ops visual overrides');
assert(!bootstrap.includes('window-material.css'),'must not load rejected experimental material layer');
assert(!bootstrap.includes('ops-r5.css'),'must not load rejected r5 palette layer');
assert(bootstrap.includes("loadStyle('./styles/network-overview.css')"),'network overview style must load');
assert(bootstrap.includes("loadStyle('./styles/theme-system.css')"),'approved native refinement must load');
assert(bootstrap.includes("loadStyle('./styles/r18-stability-hotfix.css')"),'r18 stability hotfix must remain loaded after the refinement layer');
assert(bootstrap.includes("loadStyle('./styles/r21-material-balance.css')"),'r21 material balance must load after shadow removal');
assert(!bootstrap.includes("loadScript('./js/window-drag.js'"),'rejected global movable-window runtime must remain disabled');
assert(bootstrap.includes("loadScript('./js/window-drag-local.js','Atlas local movable windows v0.16.9-r21')"),'local window drag runtime must load');
assert(bootstrap.includes('const SYNC_V2_ENABLED=false'),'automatic record-level sync must remain explicitly paused during recovery');
assert(bootstrap.includes("loadScript('./js/widget-visibility-hotfix.js','Atlas widget visibility hotfix v0.16.9-r20')"),'widget visibility hotfix must remain loaded');
assert(bootstrap.includes("if(SYNC_V2_ENABLED)"),'sync runtime must remain behind the emergency recovery gate');
assert(bootstrap.includes("loadScript('./js/sync-v2.js','Atlas record-level sync')"),'sync runtime path must remain available behind the gate');
assert(bootstrap.includes("paused:true"),'paused sync status must be exposed to the UI');
assert(bootstrap.includes("loadScript('./js/capture-flow-fix.js','Atlas capture launcher handoff v0.16.9')"),'capture handoff must remain');
assert(bootstrap.includes("loadScript('./js/network-overview.js','Atlas network overview v0.16.9')"),'network overview must remain');
assert(bootstrap.includes("loadScript('./js/sync-v2-core.js','Atlas record-level sync core')"),'record-level sync core must remain available');
assert(!bootstrap.includes("loadScript('./js/cloud-sync.js'"),'legacy whole-snapshot sync must not boot');
assert(!bootstrap.includes("loadScript('./js/cloud-sync-hotfix.js'"),'legacy snapshot hotfix must not boot');
assert(bootstrap.includes("document.documentElement.classList.add('atlas-ready')"),'boot guard must release after load');
assert(capture.includes('[data-atlas-aligned-capture]'),'capture launcher handoff contract missing');
assert(overview.includes('AtlasNetworkOverview'),'network overview runtime contract missing');
assert(!overview.includes('dataset.skin'),'network overview must not own skin state');
assert(overviewCss.includes('.atlas-network-minimap'),'network overview presentation missing');
assert(theme.includes('#atlasCaptureLauncher'),'production theme must explicitly style Capture glass');
assert(theme.includes('--atlas-float-glass'),'production theme must expose floating glass material');
assert(theme.includes('.quick-todo span'),'To-do contrast fix must remain');
assert(theme.includes('.atlas-physics-panel'),'network controls must share the glass system');
assert(hotfix.includes('box-shadow:none!important'),'decorative pane shadows must remain removed');
assert(material.includes('--atlas-float-glass:rgba(7,11,15,.38)'),'r21 night floating glass must regain material weight');
assert(material.includes('backdrop-filter:blur(3px)!important'),'r21 must preserve low-flare 3px frost');
assert(material.includes('box-shadow:none!important'),'r21 must not bring decorative shadows back');
assert(material.includes('.atlas-window-movable'),'r21 must provide local movable-window presentation');
assert(visibility.includes('scrollIntoView'),'opened docked widgets must be revealed if outside the viewport');
assert(visibility.includes('clampFloating'),'floating widgets must be clamped into the viewport');
assert(!visibility.includes('SYNC_V2_ENABLED'),'widget visibility hotfix must not own sync state');
assert(localDrag.includes("handle.addEventListener('pointerdown'"),'local drag must bind pointerdown directly to the handle');
assert(!localDrag.includes("document.addEventListener('pointerdown'"),'local drag must not intercept document pointerdown');
assert(localDrag.includes("observe(document.body,{childList:true,subtree:true})"),'local drag may discover dynamically inserted windows by child-list observation only');
assert(!localDrag.includes('attributes:true'),'local drag must not observe class/attribute mutations');
assert(sw.includes("atlas-shell-0.16.9-r21"),'r21 cache version missing');
assert(sw.includes("'./js/widget-visibility-hotfix.js'"),'widget visibility hotfix must be cached');
assert(sw.includes("'./js/window-drag-local.js'"),'local window drag runtime must be cached');
assert(sw.includes("'./styles/r21-material-balance.css'"),'r21 material balance CSS must be cached');
assert(sw.includes("'./styles/theme-system.css'"),'native refinement CSS must be cached');
assert(sw.includes("'./styles/r18-stability-hotfix.css'"),'stability hotfix CSS must be cached');
assert(!sw.includes("'./js/window-drag.js'"),'rejected global movable-window runtime must not remain in APP_SHELL');
assert(sw.includes("'./styles/network-overview.css'"),'network overview CSS must be cached');
assert(sw.includes("'./js/network-overview.js'"),'network overview runtime must be cached');
assert(sw.includes("'./js/capture-flow-fix.js'"),'capture fix must be cached');
assert(sw.includes("'./js/sync-v2-core.js'"),'record-level sync core must be cached');
assert(sw.includes("'./js/sync-v2.js'"),'sync runtime may remain cached even though boot is paused');
assert(!sw.includes("'./js/cloud-sync.js'"),'legacy snapshot sync must not be in the app shell');
assert(!sw.includes("'./js/cloud-sync-hotfix.js'"),'legacy snapshot hotfix must not be in the app shell');
assert(!sw.includes("'./assets/lock-terrain.gif'"),'removed lock artwork must not remain offline-critical');

console.log('Atlas v0.16.9-r21 material + local window drag + recovery compatibility: PASS');
