(function(){
'use strict';

var SUPA='https://tqezgmpgjoibhckhnrfw.supabase.co';
var KEY='sb_publishable_B9miQZryNJq2nWspEvJAOg_ogAAdO7H';
var ENTITY_TYPE='entity_state_v2';
var SESSION_KEY='atlas_house_legacy_session_v1';
var PAD_SESSION_KEY='atlas_pad_session_v1';
var TARGET_KEY='atlas_house_legacy_target_v1';
var CACHE_KEY='atlas_house_legacy_snapshot_v1';
var LIST_KEY='atlas_house_legacy_list_v1';
var THEME_KEY='atlas_house_legacy_theme_v1';
var WEATHER_KEY='atlas_melbourne_weather_v1';
var WEATHER_URL='https://api.open-meteo.com/v1/forecast?latitude=-37.8136&longitude=144.9631&current=temperature_2m,weather_code&timezone=Australia%2FMelbourne';
var PROFILE='us';
var session=null;
var target=null;
var records={};
var house={calendar:[],quickTodos:[],lists:[],cached:false,at:0};
var monthCursor=new Date();
var loading=false;
var mutating=false;
var toastTimer=null;
monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth(),1);

function byId(id){return document.getElementById(id)}
function clone(value){return value==null?value:JSON.parse(JSON.stringify(value))}
function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function pad2(value){value=String(value);return value.length<2?'0'+value:value}
function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function keyFor(kind,id){return String(kind)+':'+encodeURIComponent(String(id))}
function dateKey(date){return date.getFullYear()+'-'+pad2(date.getMonth()+1)+'-'+pad2(date.getDate())}
function parseDateKey(value){var parts=String(value||'').split('-');if(parts.length!==3)return null;return new Date(Number(parts[0]),Number(parts[1])-1,Number(parts[2]))}
function todayKey(){return dateKey(new Date())}
function addDays(date,days){var copy=new Date(date.getFullYear(),date.getMonth(),date.getDate());copy.setDate(copy.getDate()+days);return copy}
function profileOf(item){return item&&item.profile?String(item.profile):'me'}
function safeJSON(raw){try{return JSON.parse(raw)}catch(e){return null}}
function localGet(key){try{return localStorage.getItem(key)}catch(e){return null}}
function localSet(key,value){try{localStorage.setItem(key,value)}catch(e){}}
function localRemove(key){try{localStorage.removeItem(key)}catch(e){}}
function online(){return typeof navigator==='undefined'||navigator.onLine!==false}

function showToast(message){var el=byId('toast');if(!el)return;el.innerHTML=esc(message);el.className='toast show';if(toastTimer)clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.className='toast'},2400)}
function setSync(text){byId('syncState').innerHTML=esc(text)}
function showAuth(message){var overlay=byId('authOverlay');if(overlay)overlay.className='auth-overlay';if(message)byId('authError').innerHTML=esc(message)}
function hideAuth(){var overlay=byId('authOverlay');if(overlay)overlay.className='auth-overlay hidden';byId('authError').innerHTML=''}

function applyTheme(){var theme=localGet(THEME_KEY)||'day';document.body.className=theme==='night'?'night':'';byId('themeToggle').innerHTML=theme==='night'?'Day':'Night';var meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute('content',theme==='night'?'#090b0c':'#e9e6dc')}
function toggleTheme(){localSet(THEME_KEY,document.body.className.indexOf('night')>=0?'day':'night');applyTheme()}

function melbourneTimeParts(){var now=new Date(),time='',date='';try{time=now.toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Australia/Melbourne'});date=now.toLocaleDateString('en-AU',{weekday:'short',day:'2-digit',month:'short',timeZone:'Australia/Melbourne'})}catch(e){time=pad2(now.getHours())+':'+pad2(now.getMinutes());date=now.toDateString().slice(0,10)}return{time:time,date:date}}
function updateClock(){var now=new Date(),mel=melbourneTimeParts();byId('melTime').innerHTML=esc(mel.time);byId('melDate').innerHTML=esc(mel.date);byId('utcTime').innerHTML=pad2(now.getUTCHours())+':'+pad2(now.getUTCMinutes())}

function weatherLabel(code){code=Number(code);if(code===0)return'Clear';if(code===1||code===2)return'Fair';if(code===3)return'Cloudy';if(code===45||code===48)return'Fog';if(code===51||code===53||code===55||code===56||code===57)return'Drizzle';if(code===61||code===63||code===65||code===66||code===67)return'Rain';if(code===71||code===73||code===75||code===77)return'Snow';if(code===80||code===81||code===82||code===85||code===86)return'Showers';if(code===95||code===96||code===99)return'Storm';return'Weather'}
function weatherIcon(code){code=Number(code);if(code===0)return'☀';if(code===1||code===2)return'◑';if(code===3)return'☁';if(code===45||code===48)return'≋';if(code===51||code===53||code===55||code===56||code===57)return'⋰';if(code===61||code===63||code===65||code===66||code===67||code===80||code===81||code===82)return'☂';if(code===71||code===73||code===75||code===77||code===85||code===86)return'❄';if(code===95||code===96||code===99)return'⚡';return'·'}
function paintWeather(value,stale){if(!value)return;var temp=Math.round(Number(value.temperature));var label=weatherLabel(value.code);byId('weatherTemp').innerHTML=temp+'°';byId('weatherCondition').innerHTML=esc(label);byId('weatherIcon').innerHTML=esc(weatherIcon(value.code));byId('weatherDetail').innerHTML=stale?'Melbourne · cached':'Melbourne';byId('topWeather').innerHTML=temp+'°';byId('topCondition').innerHTML=esc(label.toUpperCase())}
function readWeather(){var value=safeJSON(localGet(WEATHER_KEY)||'null');if(!value||isNaN(Number(value.temperature))||isNaN(Number(value.code))||isNaN(Number(value.at)))return null;return value}
function loadWeather(force){var cached=readWeather(),age=cached?Date.now()-Number(cached.at):999999999;if(cached)paintWeather(cached,age>15*60*1000);if(!force&&cached&&age<15*60*1000)return Promise.resolve(cached);if(!online())return Promise.resolve(cached);return fetch(WEATHER_URL,{cache:'no-store'}).then(function(response){if(!response.ok)throw new Error('Weather unavailable');return response.json()}).then(function(payload){var current=payload&&payload.current?payload.current:null;var value={temperature:Number(current&&current.temperature_2m),code:Number(current&&current.weather_code),at:Date.now()};if(isNaN(value.temperature)||isNaN(value.code))throw new Error('Weather unavailable');localSet(WEATHER_KEY,JSON.stringify(value));paintWeather(value,false);return value}).catch(function(){if(cached)paintWeather(cached,true);return cached})}

function normaliseSession(value){if(!value||!value.access_token||!value.refresh_token)return null;if(!value.expires_at&&value.expires_in)value.expires_at=Math.floor(Date.now()/1000)+Number(value.expires_in);return value}
function readSession(){var value=normaliseSession(safeJSON(localGet(SESSION_KEY)||'null'));if(!value)value=normaliseSession(safeJSON(localGet(PAD_SESSION_KEY)||'null'));return value}
function saveSession(value){session=normaliseSession(value);if(session)localSet(SESSION_KEY,JSON.stringify(session))}
function sessionFresh(value){if(!value||!value.access_token)return false;if(!value.expires_at)return true;return Number(value.expires_at)*1000-Date.now()>120000}
function authHeaders(token){var headers={'apikey':KEY,'Content-Type':'application/json'};if(token)headers.Authorization='Bearer '+token;return headers}
function parseResponse(response){return response.text().then(function(text){var data=text?safeJSON(text):null;if(!response.ok){var message=data&&(data.error_description||data.msg||data.message||data.error)?(data.error_description||data.msg||data.message||data.error):text||('HTTP '+response.status);var error=new Error(message);error.status=response.status;throw error}return data})}
function refreshSession(value){if(!value||!value.refresh_token)return Promise.reject(new Error('Atlas sign in required.'));return fetch(SUPA+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:authHeaders(),body:JSON.stringify({refresh_token:value.refresh_token})}).then(parseResponse).then(function(next){saveSession(next);return session})}
function ensureSession(){if(!session)session=readSession();if(!session)return Promise.reject(new Error('Atlas sign in required.'));if(sessionFresh(session))return Promise.resolve(session);return refreshSession(session)}
function request(path,value,method,body,prefer){var headers=authHeaders(value.access_token),options={method:method||'GET',headers:headers};if(prefer)headers.Prefer=prefer;if(body!=null)options.body=JSON.stringify(body);return fetch(SUPA+path,options).then(parseResponse)}

function readTarget(){return safeJSON(localGet(TARGET_KEY)||'null')}
function saveTarget(value){target=value;localSet(TARGET_KEY,JSON.stringify(value))}
function resolveTarget(value){var cached=readTarget();if(cached&&cached.userId&&value.user&&cached.userId===value.user.id&&cached.profileId){target=cached;return Promise.resolve(target)}if(!value.user||!value.user.id)return Promise.reject(new Error('Atlas user session is incomplete.'));var uidValue=value.user.id;return request('/rest/v1/atlas_vaults?select=id&created_by=eq.'+encodeURIComponent(uidValue)+'&name=eq.Atlas&limit=1',value).then(function(vaults){if(!vaults||!vaults.length)throw new Error('Atlas cloud vault not found.');return request('/rest/v1/atlas_profiles?select=id&vault_id=eq.'+encodeURIComponent(vaults[0].id)+'&profile_key=eq.me&kind=eq.person&owner_user_id=eq.'+encodeURIComponent(uidValue)+'&limit=1',value)}).then(function(profiles){if(!profiles||!profiles.length)throw new Error('Atlas cloud profile not found.');var resolved={userId:uidValue,profileId:profiles[0].id};saveTarget(resolved);return resolved})}
function fetchRows(value,resolved,offset,all){var limit=500;return request('/rest/v1/atlas_records?select=record_id,payload,revision,updated_at&profile_id=eq.'+encodeURIComponent(resolved.profileId)+'&record_type=eq.'+ENTITY_TYPE+'&order=record_id.asc&limit='+limit+'&offset='+offset,value).then(function(batch){batch=batch instanceof Array?batch:[];var joined=all.concat(batch);if(batch.length<limit)return joined;return fetchRows(value,resolved,offset+limit,joined)})}

function saveHouseCache(){var snapshot={calendar:house.calendar,quickTodos:house.quickTodos,lists:house.lists,at:Date.now()};localSet(CACHE_KEY,JSON.stringify(snapshot))}
function loadHouseCache(){var snapshot=safeJSON(localGet(CACHE_KEY)||'null');if(!snapshot)return false;house={calendar:snapshot.calendar instanceof Array?snapshot.calendar:[],quickTodos:snapshot.quickTodos instanceof Array?snapshot.quickTodos:[],lists:snapshot.lists instanceof Array?snapshot.lists:[],cached:true,at:Number(snapshot.at||0)};records={};renderHouse();setSync(online()?'CACHED':'OFFLINE');return true}
function recordEntry(kind,id){return records[keyFor(kind,id)]||null}
function materialise(rows){var calendar=[],todos=[],lists=[];records={};var i,row,payload,data,key;for(i=0;i<rows.length;i++){row=rows[i]||{};payload=row.payload||null;if(!payload||payload.schema!=='atlas_entity_record'||Number(payload.version)!==2||!payload.kind||!payload.id)continue;key=keyFor(payload.kind,payload.id);records[key]={kind:payload.kind,id:payload.id,row:row,data:payload.deleted?null:clone(payload.data)};if(payload.deleted||payload.data==null)continue;data=payload.data;if(payload.kind==='calendar'&&profileOf(data)===PROFILE)calendar.push(clone(data));else if(payload.kind==='quickTodos'&&profileOf(data)===PROFILE)todos.push(clone(data));else if(payload.kind==='notes'&&profileOf(data)===PROFILE&&data.type==='list')lists.push(clone(data))}
calendar.sort(function(a,b){var ad=String(a.date||'')+' '+String(a.startTime||''),bd=String(b.date||'')+' '+String(b.startTime||'');return ad<bd?-1:ad>bd?1:0});todos.sort(function(a,b){if(!!a.done!==!!b.done)return a.done?1:-1;return Number(b.createdAt||0)-Number(a.createdAt||0)});lists.sort(function(a,b){return Number(b.updatedAt||b.createdAt||0)-Number(a.updatedAt||a.createdAt||0)});house={calendar:calendar,quickTodos:todos,lists:lists,cached:false,at:Date.now()};saveHouseCache();renderHouse()}
function loadCloud(force){if(loading&&!force)return Promise.resolve();loading=true;setSync('SYNCING');return ensureSession().then(function(value){session=value;return resolveTarget(value).then(function(resolved){return fetchRows(value,resolved,0,[])})}).then(function(rows){materialise(rows);hideAuth();setSync('SYNCED')}).catch(function(error){if(error&&error.status===401){session=null;localRemove(SESSION_KEY);showAuth('Your Atlas session expired. Sign in again.')}else if(!session){showAuth(error.message)}if(!house.at)loadHouseCache();setSync(online()?'ERROR':'OFFLINE');if(error&&error.message)showToast(error.message)}).then(function(){loading=false;renderHouse()})}

function canWrite(){return !!session&&!!target&&online()&&!mutating&&!house.cached}
function setInputs(){var enabled=canWrite();var ids=['todoInput','addTodo','listSelect','newList','listItemInput','addListItem'];var i,el;for(i=0;i<ids.length;i++){el=byId(ids[i]);if(el)el.disabled=!enabled}if(!house.lists.length){byId('listItemInput').disabled=true;byId('addListItem').disabled=true}}
function payloadFor(kind,id,data,deleted){return{schema:'atlas_entity_record',version:2,kind:String(kind),id:String(id),deleted:!!deleted,data:deleted?null:clone(data),deviceId:'house-ios12',clientMutationAt:Date.now()}}
function insertRecord(value,kind,data){var id=data.id,body={profile_id:target.profileId,record_type:ENTITY_TYPE,record_id:keyFor(kind,id),payload:payloadFor(kind,id,data,false),client_updated_at:Date.now(),updated_by:target.userId};return request('/rest/v1/atlas_records',value,'POST',body,'return=minimal')}
function updateRecord(value,kind,id,data,deleted){var entry=recordEntry(kind,id);if(!entry||!entry.row)throw new Error('House needs a refresh before editing this item.');var revision=Number(entry.row.revision||0),recordId=keyFor(kind,id);var body={payload:payloadFor(kind,id,data,deleted),client_updated_at:Date.now(),revision:revision+1,updated_by:target.userId};var path='/rest/v1/atlas_records?profile_id=eq.'+encodeURIComponent(target.profileId)+'&record_type=eq.'+ENTITY_TYPE+'&record_id=eq.'+encodeURIComponent(recordId)+'&revision=eq.'+revision+'&select=record_id,revision';return request(path,value,'PATCH',body,'return=representation').then(function(result){if(!(result instanceof Array)||!result.length)throw new Error('Atlas changed on another device. House has refreshed instead.');return result})}
function mutate(work,successMessage){if(!canWrite()){showToast(online()?'Atlas is still connecting.':'Offline — House is read-only until connection returns.');return}mutating=true;setInputs();ensureSession().then(function(value){return work(value)}).then(function(){return loadCloud(true)}).then(function(){if(successMessage)showToast(successMessage)}).catch(function(error){showToast(error&&error.message?error.message:'That change was not saved.');return loadCloud(true)}).then(function(){mutating=false;renderHouse()})}

function renderCalendar(){var events=house.calendar,year=monthCursor.getFullYear(),month=monthCursor.getMonth(),first=new Date(year,month,1),start=new Date(year,month,1-first.getDay()),html='',days=['S','M','T','W','T','F','S'],i,j,day,key,out,today,has,monthPrefix=year+'-'+pad2(month+1),count=0;for(i=0;i<events.length;i++)if(String(events[i].date||'').slice(0,7)===monthPrefix)count++;for(i=0;i<days.length;i++)html+='<div class="dow">'+days[i]+'</div>';for(i=0;i<42;i++){day=new Date(start.getFullYear(),start.getMonth(),start.getDate()+i);key=dateKey(day);out=day.getMonth()!==month;today=key===todayKey();has=false;for(j=0;j<events.length;j++)if(events[j].date===key){has=true;break}html+='<div class="mini-day'+(out?' out':'')+(today?' today':'')+(has?' has-event':'')+'">'+day.getDate()+'</div>'}byId('miniCalendar').innerHTML=html;try{byId('calendarTitle').innerHTML=first.toLocaleDateString('en-AU',{month:'short',year:'numeric'})}catch(e){byId('calendarTitle').innerHTML=pad2(month+1)+' / '+year}byId('calendarMeta').innerHTML=count+' Events · Us'}
function renderUpcoming(){var start=todayKey(),end=dateKey(addDays(new Date(),30)),events=[],i,e,limit=5,html='';for(i=0;i<house.calendar.length;i++){e=house.calendar[i];if(e.date>=start&&e.date<=end)events.push(e)}events.sort(function(a,b){var av=String(a.date||'')+' '+String(a.startTime||''),bv=String(b.date||'')+' '+String(b.startTime||'');return av<bv?-1:av>bv?1:0});byId('upcomingMeta').innerHTML=events.length+' / 30D · Us';if(!events.length){byId('upcomingList').innerHTML='<div class="widget-empty">Nothing scheduled.</div>';return}for(i=0;i<events.length&&i<limit;i++){e=events[i];html+='<div class="widget-row"><i></i><div><strong>'+esc(e.title||'Untitled event')+'</strong><small>'+esc(e.date)+(e.startTime?' · '+esc(e.startTime):'')+'</small></div><em>Us</em></div>'}if(events.length>limit)html+='<div class="more-row">+'+(events.length-limit)+' more in Atlas</div>';byId('upcomingList').innerHTML=html}
function renderTodos(){var todos=house.quickTodos,open=0,limit=3,html='',i,t;for(i=0;i<todos.length;i++)if(!todos[i].done)open++;byId('todoMeta').innerHTML=open+' Open · Us';if(!todos.length){byId('todoList').innerHTML='<div class="widget-empty">No quick tasks.</div>';return}for(i=0;i<todos.length&&i<limit;i++){t=todos[i];html+='<label class="quick-todo'+(t.done?' done':'')+'"><input type="checkbox" data-todo-id="'+esc(t.id)+'"'+(t.done?' checked':'')+(canWrite()?'':' disabled')+'><span>'+esc(t.text)+'</span><button type="button" class="quick-delete" data-delete-todo="'+esc(t.id)+'"'+(canWrite()?'':' disabled')+'>×</button></label>'}if(todos.length>limit)html+='<div class="more-row">+'+(todos.length-limit)+' more in Atlas</div>';byId('todoList').innerHTML=html}
function selectedList(){var selected=localGet(LIST_KEY)||'',lists=house.lists,i;for(i=0;i<lists.length;i++)if(lists[i].id===selected)return lists[i];if(lists.length){localSet(LIST_KEY,lists[0].id);return lists[0]}return null}
function renderLists(){var lists=house.lists,current=selectedList(),html='',i,item,items,open=0,limit=3,select='';if(lists.length){for(i=0;i<lists.length;i++)select+='<option value="'+esc(lists[i].id)+'"'+(current&&lists[i].id===current.id?' selected':'')+'>'+esc(lists[i].title||'Untitled list')+'</option>'}else select='<option value="">No lists</option>';byId('listSelect').innerHTML=select;if(!current){byId('listMeta').innerHTML='0 Lists · Us';byId('listItems').innerHTML='<div class="widget-empty">No lists yet.</div>';return}items=current.listItems instanceof Array?current.listItems:[];for(i=0;i<items.length;i++)if(!items[i].done)open++;byId('listMeta').innerHTML=open+' Open · Us';if(!items.length){byId('listItems').innerHTML='<div class="widget-empty">No items yet.</div>';return}for(i=0;i<items.length&&i<limit;i++){item=items[i];html+='<label class="quick-todo'+(item.done?' done':'')+'"><input type="checkbox" data-list-id="'+esc(current.id)+'" data-list-item-id="'+esc(item.id)+'"'+(item.done?' checked':'')+(canWrite()?'':' disabled')+'><span>'+esc(item.text)+'</span><button type="button" class="quick-delete" data-delete-list-item="'+esc(item.id)+'" data-list-id="'+esc(current.id)+'"'+(canWrite()?'':' disabled')+'>×</button></label>'}if(items.length>limit)html+='<div class="more-row">+'+(items.length-limit)+' more in Atlas</div>';byId('listItems').innerHTML=html}
function renderHouse(){renderCalendar();renderUpcoming();renderLists();renderTodos();setInputs()}

function addTodo(){var input=byId('todoInput'),text=input.value.replace(/^\s+|\s+$/g,'');if(!text)return;var data={id:uid('qt'),profile:PROFILE,text:text,done:false,createdAt:Date.now()};mutate(function(value){return insertRecord(value,'quickTodos',data)},'To-do added');input.value=''}
function toggleTodo(id,done){var entry=recordEntry('quickTodos',id);if(!entry||!entry.data)return;var data=clone(entry.data);data.done=!!done;mutate(function(value){return updateRecord(value,'quickTodos',id,data,false)},'To-do updated')}
function deleteTodo(id){var entry=recordEntry('quickTodos',id);if(!entry)return;mutate(function(value){return updateRecord(value,'quickTodos',id,null,true)},'To-do removed')}
function createList(){if(!canWrite()){showToast('Atlas is still connecting.');return}var name=window.prompt('List name');name=String(name||'').replace(/^\s+|\s+$/g,'');if(!name)return;var stamp=Date.now(),data={id:uid('n'),profile:PROFILE,space:'personal',areaId:'',topicId:'',type:'list',title:name,body:'',tags:['List'],createdAt:stamp,updatedAt:stamp,showOnMap:false,listItems:[]};localSet(LIST_KEY,data.id);mutate(function(value){return insertRecord(value,'notes',data)},'List created')}
function updateListItem(listId,itemId,done,remove){var entry=recordEntry('notes',listId);if(!entry||!entry.data)return;var data=clone(entry.data),items=data.listItems instanceof Array?data.listItems:[],next=[],i,item;for(i=0;i<items.length;i++){item=items[i];if(item.id===itemId){if(remove)continue;item=clone(item);item.done=!!done;item.updatedAt=Date.now()}next.push(item)}data.listItems=next;data.updatedAt=Date.now();mutate(function(value){return updateRecord(value,'notes',listId,data,false)},remove?'List item removed':'List updated')}
function addListItem(){var current=selectedList(),input=byId('listItemInput'),text=input.value.replace(/^\s+|\s+$/g,'');if(!current||!text)return;var entry=recordEntry('notes',current.id);if(!entry||!entry.data){showToast('Refresh House before editing this list.');return}var data=clone(entry.data),stamp=Date.now();if(!(data.listItems instanceof Array))data.listItems=[];data.listItems.push({id:uid('li'),text:text,done:false,createdAt:stamp,updatedAt:stamp});data.updatedAt=stamp;mutate(function(value){return updateRecord(value,'notes',current.id,data,false)},'List item added');input.value=''}

function signIn(){var email=byId('email').value.replace(/^\s+|\s+$/g,''),password=byId('password').value,button=byId('signIn');if(!email||!password){byId('authError').innerHTML='Enter your Atlas email and password.';return}button.disabled=true;byId('authError').innerHTML='Connecting…';fetch(SUPA+'/auth/v1/token?grant_type=password',{method:'POST',headers:authHeaders(),body:JSON.stringify({email:email,password:password})}).then(parseResponse).then(function(value){saveSession(value);localRemove(TARGET_KEY);target=null;byId('password').value='';return loadCloud(true)}).catch(function(error){showAuth(error&&error.message?error.message:'Atlas sign in failed.')}).then(function(){button.disabled=false})}
function signOut(){session=null;target=null;records={};localRemove(SESSION_KEY);localRemove(TARGET_KEY);setSync('LOCAL');showAuth('')}

function bind(){byId('themeToggle').onclick=toggleTheme;byId('refreshHouse').onclick=function(){loadWeather(true);loadCloud(true)};byId('signOut').onclick=signOut;byId('signIn').onclick=signIn;byId('calPrev').onclick=function(){monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()-1,1);renderCalendar()};byId('calNext').onclick=function(){monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()+1,1);renderCalendar()};byId('addTodo').onclick=addTodo;byId('todoInput').onkeydown=function(event){event=event||window.event;if((event.keyCode||event.which)===13){if(event.preventDefault)event.preventDefault();addTodo();return false}};byId('todoList').onchange=function(event){event=event||window.event;var el=event.target||event.srcElement,id=el.getAttribute('data-todo-id');if(id)toggleTodo(id,el.checked)};byId('todoList').onclick=function(event){event=event||window.event;var el=event.target||event.srcElement,id=el.getAttribute('data-delete-todo');if(id)deleteTodo(id)};byId('listSelect').onchange=function(){localSet(LIST_KEY,this.value);renderLists();setInputs()};byId('newList').onclick=createList;byId('addListItem').onclick=addListItem;byId('listItemInput').onkeydown=function(event){event=event||window.event;if((event.keyCode||event.which)===13){if(event.preventDefault)event.preventDefault();addListItem();return false}};byId('listItems').onchange=function(event){event=event||window.event;var el=event.target||event.srcElement,listId=el.getAttribute('data-list-id'),itemId=el.getAttribute('data-list-item-id');if(listId&&itemId)updateListItem(listId,itemId,el.checked,false)};byId('listItems').onclick=function(event){event=event||window.event;var el=event.target||event.srcElement,itemId=el.getAttribute('data-delete-list-item'),listId=el.getAttribute('data-list-id');if(listId&&itemId)updateListItem(listId,itemId,false,true)};byId('password').onkeydown=function(event){event=event||window.event;if((event.keyCode||event.which)===13)signIn()};window.addEventListener('online',function(){setSync('SYNCING');loadCloud(true);loadWeather(true)});window.addEventListener('offline',function(){setSync('OFFLINE');renderHouse()});document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible'){loadWeather(false);loadCloud(false)}})}
function init(){applyTheme();bind();updateClock();setInterval(updateClock,30000);loadHouseCache();loadWeather(false);session=readSession();if(session){hideAuth();loadCloud(true)}else showAuth('');setInterval(function(){if(document.visibilityState!=='hidden'&&online()){loadCloud(false);loadWeather(false)}},5*60*1000)}

init();
}());
